version: 2
updates:
  ## Register
  - directory: "src/"
    package-ecosystem: "nuget"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "07:00"
      timezone: "Europe/Oslo"

## Test
  - directory: "test/"
    package-ecosystem: "nuget"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "07:00"
      timezone: "Europe/Oslo"