version: 2
updates:
  ## Register
  - directory: "src/Register"
    package-ecosystem: "nuget"
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "07:00"
      timezone: "Europe/Oslo"

## Test
  - directory: "test/Altinn.Platform.Register.Tests"
    package-ecosystem: "nuget"
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "07:00"
      timezone: "Europe/Oslo"
