version: 2
updates:
  ## Register
  - directory: "src/Register"
    package-ecosystem: "nuget"
    schedule:
      interval: "daily"
      ##day: "thursday"
      time: "07:00"
      timezone: "Europe/Oslo"

## Test
  - directory: "test/Altinn.Platform.Register.Tests"
    package-ecosystem: "nuget"
    schedule:
      interval: "daily"
      ##day: "thursday"
      time: "07:00"
      timezone: "Europe/Oslo"

## Dockerfile
  - directory: "/"
    package-ecosystem: "docker"
    schedule:
      interval: "daily"
      ##day: "thursday"
      time: "07:00"
      timezone: "Europe/Oslo"

## GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      ##day: "thursday"
      time: "07:00"
      timezone: "Europe/Oslo"
vg

