import {
  getGuardianships,
  type GuardianshipDefinition,
  type LocalizedString,
} from "./lib/guardianships.mts";

const escapeLiteral = function (str: string) {
  let hasBackslash = false;
  let escaped = "'";

  if (str == null) {
    return "''";
  }

  for (let i = 0; i < str.length; i++) {
    const c = str[i];
    if (c === "'") {
      escaped += c + c;
    } else if (c === "\\") {
      escaped += c + c;
      hasBackslash = true;
    } else {
      escaped += c;
    }
  }

  escaped += "'";

  if (hasBackslash === true) {
    escaped = " E" + escaped;
  }

  return escaped;
};

const indent = (lines: string[], indentation: string = "  "): string[] =>
  lines.map((line) => `${indentation}${line}`);

const suffixLast = (lines: string[], suffix: string = ","): string[] =>
  lines.map((line, index, array) =>
    index === array.length - 1 ? `${line}${suffix}` : line
  );

const formatLocalizedString = (localized: LocalizedString) => {
  const valueLines = Object.entries(localized).map(
    ([lang, value], index, array) => {
      const start = `${escapeLiteral(lang)}, ${escapeLiteral(value)}`;
      return index < array.length - 1 ? `${start},` : start;
    }
  );

  return ["hstore(ARRAY[", ...indent(valueLines), "])"];
};

const sourceLine = `${escapeLiteral("cra")},`;
const formatGuardianshipValues = (guardianship: GuardianshipDefinition) => {
  const identifierLine = `${escapeLiteral(guardianship.identifier)},`;
  const nameLines = suffixLast(formatLocalizedString(guardianship.title));
  const descriptionLines = formatLocalizedString(guardianship.description);

  return [sourceLine, identifierLine, ...nameLines, ...descriptionLines];
};

const guardianships = await getGuardianships();
if (guardianships.length === 0) {
  throw new Error("No guardianships found to generate migration for.");
}

const lines = [
  "-- Generated by `just generate-guardianship-migration`",
  "-- Do not edit manually",
  "",
  `INSERT INTO register.external_role_definition ("source", "identifier", "name", "description") VALUES`,
];

let first = true;
for (const g of guardianships) {
  lines.push(first ? "  (" : ", (");
  first = false;

  lines.push(...indent(formatGuardianshipValues(g), "     "));
  lines.push("  )");
}

lines.push("ON CONFLICT (source, identifier) DO UPDATE");
lines.push(`    SET "name" = EXCLUDED."name",`);
lines.push(`        "description" = EXCLUDED."description";`);

console.log(lines.join("\n"));
