import { getAreas, type GuardianshipArea } from "./lib/guardianships.mts";
import { type TrieNode } from "./lib/trie.mts";

const { map: areas } = await getAreas();

const INDENT = "    ";

function ind(line: string, indentation: string = INDENT): string {
  if (line.length === 0) return ``;
  else return `${indentation}${line}`;
}

function* indent(
  lines: Iterable<string>,
  indentation: string = INDENT,
): Iterable<string> {
  for (const line of lines) {
    yield ind(line, indentation);
  }
}

function* guardianshipMetas(): Iterable<string> {
  for (const area of areas.values()) {
    for (const task of area.tasks.values()) {
      yield `new GuardianshipMetadata`;
      yield `{`;
      yield ind(`Identifier = "${task.guardianship.identifier}",`);
      yield ind(
        `Role = GuardianshipRoles.${area.identifier}.${task.identifier},`,
      );
      yield ind(`NprArea = "${area.mapping.npr}",`);
      yield ind(`NprTask = "${task.mapping.npr}",`);
      yield `},`;
    }
  }
}

const lines = [
  `// This file is autogenerated. Do not edit directly.`,
  `#nullable enable`,
  ``,
  `using Altinn.Register.Contracts;`,
  `using Altinn.Register.Contracts.ExternalRoles;`,
  `using Altinn.Register.PartyImport.Npr;`,
  `using System.Diagnostics.CodeAnalysis;`,
  ``,
  `namespace Altinn.Register.Tests.PartyImport.Npr;`,
  ``,
  `/// <summary>Tests for mapping of guardianship roles.</summary>`,
  `public static partial class GuardianshipRoleMapperTests`,
  `{`,
  ...indent([
    `private static partial TheoryData<GuardianshipMetadata> GetGuardianshipRoles()`,
    `{`,
    ind(`return new([`),
    ...indent(indent(guardianshipMetas())),
    ind(`]);`),
    `}`,
  ]),
  `}`,
];

console.log(lines.join("\n"));
