// This file is autogenerated. Do not edit directly.
#nullable enable

using Altinn.Register.Contracts;
using Altinn.Register.Contracts.ExternalRoles;
using System.Diagnostics.CodeAnalysis;

namespace Altinn.Register.PartyImport.Npr;

/// <summary>Roles for guardianships.</summary>
internal static partial class GuardianshipRoles
{
    /// <summary>Roles for guardianships in the area 'Bank'.</summary>
    public static partial class Bank
    {
        /// <summary>Omfatter oppgaver knyttet til å opprette kundeforhold, opprette/avslutte konto, disposisjonsrett, etablere/endre betalingsavtaler og forvalte låneavtaler</summary>
        public static ExternalRoleReference RepresentasjonDagligbank { get; } = new(ExternalRoleSource.CivilRightsAuthority, "bank-representasjon-dagligbank");

        /// <summary>Gjelder søknad om etablering av banklån - dette krever statsforvalterens samtykke</summary>
        public static ExternalRoleReference TaOppLånKreditter { get; } = new(ExternalRoleSource.CivilRightsAuthority, "bank-ta-opp-lan-kreditter");
    }

    /// <summary>Roles for guardianships in the area 'Forsikringsselskap'.</summary>
    public static partial class Forsikringsselskap
    {
        /// <summary>Omfatter oppgaver knyttet til å etablere/endre/avslutte forsikringsavtaler og representasjon ved forsikringsoppgjør</summary>
        public static ExternalRoleReference ForvalteForsikringsavtaler { get; } = new(ExternalRoleSource.CivilRightsAuthority, "forsikringsselskap-forvalte-forsikringsavtaler");
    }

    /// <summary>Roles for guardianships in the area 'Helfo'.</summary>
    public static partial class Helfo
    {
        /// <summary>Gjelder bistand til å søke om stønad til helsetjenester etter folketrygdloven, herunder innsyn i og håndtering av egenandel-/frikortordningen og helsetjenester gitt i utlandet. Gjelder også når en tredjepart sender søknad på vegne av en person (eks. lege, arbeidsgiver, forsikringsselskap)</summary>
        public static ExternalRoleReference RefusjonForPrivatpersoner { get; } = new(ExternalRoleSource.CivilRightsAuthority, "helfo-refusjon-privatpersoner");

        /// <summary>Gjelder bistand til å bytte fastlege, samt å kunne se tidligere og nåværende fastlege</summary>
        public static ExternalRoleReference Fastlege { get; } = new(ExternalRoleSource.CivilRightsAuthority, "helfo-fastlege");
    }

    /// <summary>Roles for guardianships in the area 'Husbanken'.</summary>
    public static partial class Husbanken
    {
        /// <summary>Gjelder søknad om og/eller eventuelt klage på vedtak om statlig bostøtte hos Husbanken</summary>
        public static ExternalRoleReference Bostøtte { get; } = new(ExternalRoleSource.CivilRightsAuthority, "husbanken-bostotte");

        /// <summary>Gjelder søknad om og/eller eventuelt klage på vedtak om startlån hos Husbanken</summary>
        public static ExternalRoleReference Startlån { get; } = new(ExternalRoleSource.CivilRightsAuthority, "husbanken-startlan");
    }

    /// <summary>Roles for guardianships in the area 'Inkassoselskap'.</summary>
    public static partial class Inkassoselskap
    {
        /// <summary>Gjelder avtaleinngåelse og forhandling med ulike inkassoselskaper</summary>
        public static ExternalRoleReference ForhandleOgInngåInkassoavtaler { get; } = new(ExternalRoleSource.CivilRightsAuthority, "inkassoselskap-inkassoavtaler");
    }

    /// <summary>Roles for guardianships in the area 'Kartverket'.</summary>
    public static partial class Kartverket
    {
        /// <summary>Omfatter emnene tinglyse eierskifte, sletting av rettighet/servitutt/heftelse, sikringspant. Tjenesteområdet vil også gjelde for overføring av fast eiendom/borettslagsandel mellom ektefeller/samboere - dette krever statsforvalterens samtykke</summary>
        public static ExternalRoleReference SalgAvFastEiendomBorettslagsandel { get; } = new(ExternalRoleSource.CivilRightsAuthority, "kartverket-salg-fast-eiendom-borettslagsandel");

        /// <summary>Omfatter emnene tinglyse eierskifte, pantsette eiendom, tinglyse avtaler (rettighet/servitutt/heftelse) og festekontrakt - dette krever statsforvalterens samtykke</summary>
        public static ExternalRoleReference KjøpAvEiendom { get; } = new(ExternalRoleSource.CivilRightsAuthority, "kartverket-kjop-eiendom");

        /// <summary>Omfatter emnene hjemmelserklæring og skjøte videre - dette krever statsforvalterens samtykke</summary>
        public static ExternalRoleReference ArvPrivatSkifteOgUskifte { get; } = new(ExternalRoleSource.CivilRightsAuthority, "kartverket-arv-privat-skifte-uskifte");

        /// <summary>Omfatter emnene seksjonering, reseksjonering, fradelinger, sammenslåinger, registreringer av festegrunn, endringer av festenummer til bruksnummer, arealoverføring - dette krever statsforvalterens samtykke</summary>
        public static ExternalRoleReference EndringAvEiendom { get; } = new(ExternalRoleSource.CivilRightsAuthority, "kartverket-endring-eiendom");

        /// <summary>Omfatter emnene tinglyse avtaler (rettighet/servitutt/heftelse) og festekontrakt, tinglysning av prioritetsbestemmelser, nedkvitteringer, tinglysing på ny, transport av frivillige heftelser og tvangsforretninger, massetransport - dette krever statsforvalterens samtykke</summary>
        public static ExternalRoleReference AvtalerOgRettigheter { get; } = new(ExternalRoleSource.CivilRightsAuthority, "kartverket-avtaler-rettigheter");

        /// <summary>Gjelder sletting av rettigheter i fast eiendom - dette krever statsforvalterens samtykke</summary>
        public static ExternalRoleReference Sletting { get; } = new(ExternalRoleSource.CivilRightsAuthority, "kartverket-sletting");

        /// <summary>Omfatter emnene pantsette eiendom, refinansiering - dette krever statsforvalterens samtykke</summary>
        public static ExternalRoleReference Låneopptak { get; } = new(ExternalRoleSource.CivilRightsAuthority, "kartverket-laneopptak");
    }

    /// <summary>Roles for guardianships in the area 'Kommune'.</summary>
    public static partial class Kommune
    {
        /// <summary>Omfatter oppgaver som hører inn under områdene bygging, eiendom, kjøp og salg, leie og utleie, samt priser og gebyr for bygg og eiendom</summary>
        public static ExternalRoleReference ByggOgEiendom { get; } = new(ExternalRoleSource.CivilRightsAuthority, "kommune-bygg-eiendom");

        /// <summary>Omfatter tilbud og støtteordninger som hører inn under områdene avlastning og støtte, helsetjenester, omsorgstjenester og velferdsstøtte</summary>
        public static ExternalRoleReference HelseOgOmsorg { get; } = new(ExternalRoleSource.CivilRightsAuthority, "kommune-helse-omsorg");

        /// <summary>Omfatter oppgaver som hører inn under områdene arbeidsgiveravgift, kommunale avgifter, eiendomsskatt og skatteattest</summary>
        public static ExternalRoleReference SkattOgAvgift { get; } = new(ExternalRoleSource.CivilRightsAuthority, "kommune-skatt-avgift");

        /// <summary>Omfatter tilbud og støtteordninger som hører inn under områdene botilbud, kvalifisering til arbeid, økonomiske ytelser og rådgivning</summary>
        public static ExternalRoleReference SosialeTjenester { get; } = new(ExternalRoleSource.CivilRightsAuthority, "kommune-sosiale-tjenester");

        /// <summary>Omfatter tilbud og støtteordninger som hører inn under områdene grunnskole, videregående skole, høyere utdanning, voksenopplæring og skolehverdag</summary>
        public static ExternalRoleReference SkoleOgUtdanning { get; } = new(ExternalRoleSource.CivilRightsAuthority, "kommune-skole-utdanning");
    }

    /// <summary>Roles for guardianships in the area 'Kredittvurderingsselskap'.</summary>
    public static partial class Kredittvurderingsselskap
    {
        /// <summary>Gjelder avtaleinngåelse om kredittsperre</summary>
        public static ExternalRoleReference Kredittsperre { get; } = new(ExternalRoleSource.CivilRightsAuthority, "kredittvurderingsselskap-kredittsperre");
    }

    /// <summary>Roles for guardianships in the area 'Namsmannen'.</summary>
    public static partial class Namsmannen
    {
        /// <summary>Gjelder søknad om og/eller forvaltning av eksisterende gjeldsordninger</summary>
        public static ExternalRoleReference Gjeldsordning { get; } = new(ExternalRoleSource.CivilRightsAuthority, "namsmannen-gjeldsordning");

        /// <summary>Gjelder representasjon i saker om tvangsfullbyrdelse etter tvangsfullbyrdelsesloven</summary>
        public static ExternalRoleReference Tvangsfullbyrdelse { get; } = new(ExternalRoleSource.CivilRightsAuthority, "namsmannen-tvangsfullbyrdelse");
    }

    /// <summary>Roles for guardianships in the area 'Nav'.</summary>
    public static partial class Nav
    {
        /// <summary>Omfatter tilbud og støtteordninger som hører inn under områdene forsikring/sykepenger (selvstendig næringsdrivende og frilansere), sykepenger, tilleggsstønad og yrkesskade/menerstatning og arbeidsavklaringspenger. Gjelder innsyn/saksbehandling og utbetaling</summary>
        public static ExternalRoleReference Arbeid { get; } = new(ExternalRoleSource.CivilRightsAuthority, "nav-arbeid");

        /// <summary>Omfatter tilbud og støtteordninger som hører inn under områdene barnebidrag, barnetrygd, enslig forsørger, foreldre- og svangerskapspenger, grunn- og hjelpestønad og kontantstøtte. Gjelder innsyn/saksbehandling og utbetaling</summary>
        public static ExternalRoleReference Familie { get; } = new(ExternalRoleSource.CivilRightsAuthority, "nav-familie");

        /// <summary>Omfatter emnene hjelpemidler, helsetjenester, ortopediske hjelpemidler og bil</summary>
        public static ExternalRoleReference Hjelpemidler { get; } = new(ExternalRoleSource.CivilRightsAuthority, "nav-hjelpemidler");

        /// <summary>Omfatter tilbud og støtteordninger som hører inn under områdene alderspensjon, supplerende stønad, uførepensjon/-trygd, avtalefestet pensjon, ytelser for gjenlevende (alle typer pensjonsytelser). Gjelder innsyn/saksbehandling og utbetaling</summary>
        public static ExternalRoleReference Pensjon { get; } = new(ExternalRoleSource.CivilRightsAuthority, "nav-pensjon");

        /// <summary>Omfatter tilbud og støtteordninger som hører inn under områdene gjeldsrådgivning, kvalifiseringsprogrammet, midlertidig botilbud, økonomisk rådgivning, forsvarlig livsopphold, midlertidig inntektssikring og økonomisk stønad. Gjelder innsyn/saksbehandling og utbetaling</summary>
        public static ExternalRoleReference SosialeTjenester { get; } = new(ExternalRoleSource.CivilRightsAuthority, "nav-sosiale-tjenester");
    }

    /// <summary>Roles for guardianships in the area 'Pasientreiser'.</summary>
    public static partial class Pasientreiser
    {
        /// <summary>Søknad om og/eller eventuell klage på vedtak om refusjon av reiseutgifter i forbindelse med behandlinger som dekkes av det offentlige</summary>
        public static ExternalRoleReference RefusjonAvPasientreiser { get; } = new(ExternalRoleSource.CivilRightsAuthority, "pasientreiser-refusjon-pasientreiser");
    }

    /// <summary>Roles for guardianships in the area 'Skatteetaten'.</summary>
    public static partial class Skatteetaten
    {
        /// <summary>Gjelder oppfølging og behandling av krav fra Skatteetaten, for eksempel restskatt</summary>
        public static ExternalRoleReference Innkreving { get; } = new(ExternalRoleSource.CivilRightsAuthority, "skatteetaten-innkreving");

        /// <summary>Gjelder endring av postadresse for person med verge</summary>
        public static ExternalRoleReference EndrePostadresse { get; } = new(ExternalRoleSource.CivilRightsAuthority, "skatteetaten-endre-postadresse");

        /// <summary>Gjelder endring av bostedsadresse</summary>
        public static ExternalRoleReference MeldeFlytting { get; } = new(ExternalRoleSource.CivilRightsAuthority, "skatteetaten-melde-flytting");

        /// <summary>Gjelder innsyn i skattedata, og representasjon overfor skattemyndighetene i alle saker om skatteforhold, herunder endring av skattekort, levering av skattemelding, skatteoppgjør og det ordinære løpet for restskatt eller penger til gode.</summary>
        public static ExternalRoleReference Skatt { get; } = new(ExternalRoleSource.CivilRightsAuthority, "skatteetaten-skatt");
    }

    /// <summary>Roles for guardianships in the area 'Statens innkrevingssentral'.</summary>
    public static partial class StatensInnkrevingssentral
    {
        /// <summary>Gjelder søknad om og forvaltning av gjeldsordning og betalingsavtaler</summary>
        public static ExternalRoleReference GjeldsordningOgBetalingsavtaler { get; } = new(ExternalRoleSource.CivilRightsAuthority, "statens-innkrevingssentral-gjeldsordning-betalingsavtaler");
    }

    /// <summary>Roles for guardianships in the area 'Statsforvalter'.</summary>
    public static partial class Statsforvalter
    {
        /// <summary>Gjelder søknad om disposisjoner som krever statsforvalterens samtykke</summary>
        public static ExternalRoleReference SøkeOmSamtykkeTilDisposisjon { get; } = new(ExternalRoleSource.CivilRightsAuthority, "statsforvalter-soke-om-samtykke-disposisjon");
    }

    /// <summary>Roles for guardianships in the area 'Tingretten'.</summary>
    public static partial class Tingretten
    {
        /// <summary>Gjelder melding om uskiftet bo jf. vgml. § 41 (3) og arvl. §§ 14 og 32 - dette krever statsforvalterens samtykke</summary>
        public static ExternalRoleReference BegjæreUskifte { get; } = new(ExternalRoleSource.CivilRightsAuthority, "tingretten-begjaere-uskifte");

        /// <summary>Omfatter tilfeller der vergen på vegne av vergehaveren overtar boet til privat skifte og ivaretakelse av andre rettigheter som arving</summary>
        public static ExternalRoleReference PrivatSkifteAvDødsbo { get; } = new(ExternalRoleSource.CivilRightsAuthority, "tingretten-privat-skifte-dodsbo");

        /// <summary>Gjelder skifte av uskiftebo jf. vgml. § 41 (3) og arvl. §§ 28 og 29 - dette krever statsforvalterens samtykke</summary>
        public static ExternalRoleReference BegjæreSkifteAvUskiftebo { get; } = new(ExternalRoleSource.CivilRightsAuthority, "tingretten-begjaere-skifte-uskiftebo");
    }

    /// <summary>Roles for guardianships in the area 'Øvrige'.</summary>
    public static partial class Øvrige
    {
        /// <summary>Gjelder i forbindelse med kjøp av varer og tjenester, omfatter også heving av avtaler, reklamasjon mm.</summary>
        public static ExternalRoleReference KjøpLeieAvVarerOgTjenester { get; } = new(ExternalRoleSource.CivilRightsAuthority, "ovrige-kjop-leie-varer-tjenester");

        /// <summary>Gjelder i forbindelse med inngåelse av husleiekontrakter</summary>
        public static ExternalRoleReference InngåelseAvHusleiekontrakter { get; } = new(ExternalRoleSource.CivilRightsAuthority, "ovrige-inngaelse-husleiekontrakter");

        /// <summary>Gjelder i forbindelse med avslutning av husleiekontrakter</summary>
        public static ExternalRoleReference AvslutningAvHusleiekontrakter { get; } = new(ExternalRoleSource.CivilRightsAuthority, "ovrige-avslutning-husleiekontrakter");

        /// <summary>Gjelder salg av løsøre av større verdi (herunder bil), usedvanlig karakter eller av spesiell interesse for vergehaver eller dennes nærmeste familie - dette krever statsforvalterens samtykke</summary>
        public static ExternalRoleReference SalgAvLøsøreAvStørreVerdi { get; } = new(ExternalRoleSource.CivilRightsAuthority, "ovrige-salg-losore-storre-verdi");

        /// <summary>Gjelder adgangen til å bruke vergehaverens inntekter til å betale regninger, betjene gjeld, og dekke øvrige utgifter</summary>
        public static ExternalRoleReference DisponereInntekterTilÅDekkeUtgifter { get; } = new(ExternalRoleSource.CivilRightsAuthority, "ovrige-disponere-inntekter-dekke-utgifter");
    }
}

/// <summary>Mappings of guardianship values from npr to Altinn Register.</summary>
internal static partial class GuardianshipRoleMapper
{
#pragma warning disable CS0164 // Unreferenced label
    /// <summary>Tries to find a guardianship role by NPR values.</summary>
    /// <param name="vergeTjenestevirksomhet">The NPR value for the guardianship area.</param>
    /// <param name="vergeTjenesteoppgave">The NPR value for the guardianship task.</param>
    /// <param name="role">The found role, if any.</param>
    /// <returns><see langword="true"/> if a role was found; otherwise, <see langword="false"/>.</returns>
    public static bool TryFindRoleByNprValues(
        ReadOnlySpan<char> vergeTjenestevirksomhet,
        ReadOnlySpan<char> vergeTjenesteoppgave,
        [NotNullWhen(true)] out ExternalRoleReference? role)
    {
        var s = vergeTjenestevirksomhet;
        if (s.Length is < 3 or > 25)
        {
            goto end;
        }

        if (s.StartsWith("h"))
        {
            var s_0 = s.Slice(1);
            if (s_0.Length is < 4 or > 8)
            {
                goto end;
            }

            if (s_0.SequenceEqual("elfo"))
            {
                return TryFindHelfoRoleByNprValue(vergeTjenesteoppgave, out role);
            }

            if (s_0.SequenceEqual("usbanken"))
            {
                return TryFindHusbankenRoleByNprValue(vergeTjenesteoppgave, out role);
            }

            goto end;
        }

        if (s.StartsWith("k"))
        {
            var s_1 = s.Slice(1);
            if (s_1.Length is < 6 or > 23)
            {
                goto end;
            }

            if (s_1.SequenceEqual("ommune"))
            {
                return TryFindKommuneRoleByNprValue(vergeTjenesteoppgave, out role);
            }

            if (s_1.SequenceEqual("artverket"))
            {
                return TryFindKartverketRoleByNprValue(vergeTjenesteoppgave, out role);
            }

            if (s_1.SequenceEqual("redittvurderingsselskap"))
            {
                return TryFindKredittvurderingsselskapRoleByNprValue(vergeTjenesteoppgave, out role);
            }

            goto end;
        }

        if (s.StartsWith("s"))
        {
            var s_2 = s.Slice(1);
            if (s_2.Length is < 11 or > 24)
            {
                goto end;
            }

            if (s_2.StartsWith("tat"))
            {
                var s_2_0 = s_2.Slice(3);
                if (s_2_0.Length is < 10 or > 21)
                {
                    goto end;
                }

                if (s_2_0.SequenceEqual("sforvalter"))
                {
                    return TryFindStatsforvalterRoleByNprValue(vergeTjenesteoppgave, out role);
                }

                if (s_2_0.SequenceEqual("ensInnkrevingssentral"))
                {
                    return TryFindStatensInnkrevingssentralRoleByNprValue(vergeTjenesteoppgave, out role);
                }

                goto end;
            }

            if (s_2.SequenceEqual("katteetaten"))
            {
                return TryFindSkatteetatenRoleByNprValue(vergeTjenesteoppgave, out role);
            }

            goto end;
        }

        if (s.StartsWith("na"))
        {
            var s_3 = s.Slice(2);
            if (s_3.Length is < 1 or > 8)
            {
                goto end;
            }

            if (s_3.SequenceEqual("v"))
            {
                return TryFindNavRoleByNprValue(vergeTjenesteoppgave, out role);
            }

            if (s_3.SequenceEqual("msmannen"))
            {
                return TryFindNamsmannenRoleByNprValue(vergeTjenesteoppgave, out role);
            }

            goto end;
        }

        if (s.SequenceEqual("bank"))
        {
            return TryFindBankRoleByNprValue(vergeTjenesteoppgave, out role);
        }

        if (s.SequenceEqual("oevrige"))
        {
            return TryFindØvrigeRoleByNprValue(vergeTjenesteoppgave, out role);
        }

        if (s.SequenceEqual("tingretten"))
        {
            return TryFindTingrettenRoleByNprValue(vergeTjenesteoppgave, out role);
        }

        if (s.SequenceEqual("pasientreiser"))
        {
            return TryFindPasientreiserRoleByNprValue(vergeTjenesteoppgave, out role);
        }

        if (s.SequenceEqual("inkassoselskap"))
        {
            return TryFindInkassoselskapRoleByNprValue(vergeTjenesteoppgave, out role);
        }

        if (s.SequenceEqual("forsikringsselskap"))
        {
            return TryFindForsikringsselskapRoleByNprValue(vergeTjenesteoppgave, out role);
        }

        end:
        role = null;
        return false;
    }

    /// <summary>Tries to find a guardianship role by NPR values.</summary>
    /// <param name="vergeTjenestevirksomhet">The NPR value for the guardianship area.</param>
    /// <param name="vergeTjenesteoppgave">The NPR value for the guardianship task.</param>
    /// <param name="role">The found role, if any.</param>
    /// <returns><see langword="true"/> if a role was found; otherwise, <see langword="false"/>.</returns>
    public static bool TryFindRoleByNprValues(
        ReadOnlySpan<byte> vergeTjenestevirksomhet,
        ReadOnlySpan<byte> vergeTjenesteoppgave,
        [NotNullWhen(true)] out ExternalRoleReference? role)
    {
        var s = vergeTjenestevirksomhet;
        if (s.Length is < 3 or > 25)
        {
            goto end;
        }

        if (s.StartsWith("h"u8))
        {
            var s_0 = s.Slice(1);
            if (s_0.Length is < 4 or > 8)
            {
                goto end;
            }

            if (s_0.SequenceEqual("elfo"u8))
            {
                return TryFindHelfoRoleByNprValue(vergeTjenesteoppgave, out role);
            }

            if (s_0.SequenceEqual("usbanken"u8))
            {
                return TryFindHusbankenRoleByNprValue(vergeTjenesteoppgave, out role);
            }

            goto end;
        }

        if (s.StartsWith("k"u8))
        {
            var s_1 = s.Slice(1);
            if (s_1.Length is < 6 or > 23)
            {
                goto end;
            }

            if (s_1.SequenceEqual("ommune"u8))
            {
                return TryFindKommuneRoleByNprValue(vergeTjenesteoppgave, out role);
            }

            if (s_1.SequenceEqual("artverket"u8))
            {
                return TryFindKartverketRoleByNprValue(vergeTjenesteoppgave, out role);
            }

            if (s_1.SequenceEqual("redittvurderingsselskap"u8))
            {
                return TryFindKredittvurderingsselskapRoleByNprValue(vergeTjenesteoppgave, out role);
            }

            goto end;
        }

        if (s.StartsWith("s"u8))
        {
            var s_2 = s.Slice(1);
            if (s_2.Length is < 11 or > 24)
            {
                goto end;
            }

            if (s_2.StartsWith("tat"u8))
            {
                var s_2_0 = s_2.Slice(3);
                if (s_2_0.Length is < 10 or > 21)
                {
                    goto end;
                }

                if (s_2_0.SequenceEqual("sforvalter"u8))
                {
                    return TryFindStatsforvalterRoleByNprValue(vergeTjenesteoppgave, out role);
                }

                if (s_2_0.SequenceEqual("ensInnkrevingssentral"u8))
                {
                    return TryFindStatensInnkrevingssentralRoleByNprValue(vergeTjenesteoppgave, out role);
                }

                goto end;
            }

            if (s_2.SequenceEqual("katteetaten"u8))
            {
                return TryFindSkatteetatenRoleByNprValue(vergeTjenesteoppgave, out role);
            }

            goto end;
        }

        if (s.StartsWith("na"u8))
        {
            var s_3 = s.Slice(2);
            if (s_3.Length is < 1 or > 8)
            {
                goto end;
            }

            if (s_3.SequenceEqual("v"u8))
            {
                return TryFindNavRoleByNprValue(vergeTjenesteoppgave, out role);
            }

            if (s_3.SequenceEqual("msmannen"u8))
            {
                return TryFindNamsmannenRoleByNprValue(vergeTjenesteoppgave, out role);
            }

            goto end;
        }

        if (s.SequenceEqual("bank"u8))
        {
            return TryFindBankRoleByNprValue(vergeTjenesteoppgave, out role);
        }

        if (s.SequenceEqual("oevrige"u8))
        {
            return TryFindØvrigeRoleByNprValue(vergeTjenesteoppgave, out role);
        }

        if (s.SequenceEqual("tingretten"u8))
        {
            return TryFindTingrettenRoleByNprValue(vergeTjenesteoppgave, out role);
        }

        if (s.SequenceEqual("pasientreiser"u8))
        {
            return TryFindPasientreiserRoleByNprValue(vergeTjenesteoppgave, out role);
        }

        if (s.SequenceEqual("inkassoselskap"u8))
        {
            return TryFindInkassoselskapRoleByNprValue(vergeTjenesteoppgave, out role);
        }

        if (s.SequenceEqual("forsikringsselskap"u8))
        {
            return TryFindForsikringsselskapRoleByNprValue(vergeTjenesteoppgave, out role);
        }

        end:
        role = null;
        return false;
    }

    private static bool TryFindBankRoleByNprValue(
        ReadOnlySpan<char> vergeTjenesteoppgave,
        [NotNullWhen(true)] out ExternalRoleReference? role)
    {
        var s = vergeTjenesteoppgave;
        if (s.Length is < 18 or > 24)
        {
            goto end;
        }

        if (s.SequenceEqual("taOppLaanKreditter"))
        {
            role = GuardianshipRoles.Bank.TaOppLånKreditter;
            return true;
        }

        if (s.SequenceEqual("representasjonDagligbank"))
        {
            role = GuardianshipRoles.Bank.RepresentasjonDagligbank;
            return true;
        }

        end:
        role = null;
        return false;
    }

    private static bool TryFindBankRoleByNprValue(
        ReadOnlySpan<byte> vergeTjenesteoppgave,
        [NotNullWhen(true)] out ExternalRoleReference? role)
    {
        var s = vergeTjenesteoppgave;
        if (s.Length is < 18 or > 24)
        {
            goto end;
        }

        if (s.SequenceEqual("taOppLaanKreditter"u8))
        {
            role = GuardianshipRoles.Bank.TaOppLånKreditter;
            return true;
        }

        if (s.SequenceEqual("representasjonDagligbank"u8))
        {
            role = GuardianshipRoles.Bank.RepresentasjonDagligbank;
            return true;
        }

        end:
        role = null;
        return false;
    }

    private static bool TryFindForsikringsselskapRoleByNprValue(
        ReadOnlySpan<char> vergeTjenesteoppgave,
        [NotNullWhen(true)] out ExternalRoleReference? role)
    {
        var s = vergeTjenesteoppgave;
        if (s.SequenceEqual("forvalteForsikringsavtaler"))
        {
            role = GuardianshipRoles.Forsikringsselskap.ForvalteForsikringsavtaler;
            return true;
        }

        end:
        role = null;
        return false;
    }

    private static bool TryFindForsikringsselskapRoleByNprValue(
        ReadOnlySpan<byte> vergeTjenesteoppgave,
        [NotNullWhen(true)] out ExternalRoleReference? role)
    {
        var s = vergeTjenesteoppgave;
        if (s.SequenceEqual("forvalteForsikringsavtaler"u8))
        {
            role = GuardianshipRoles.Forsikringsselskap.ForvalteForsikringsavtaler;
            return true;
        }

        end:
        role = null;
        return false;
    }

    private static bool TryFindHelfoRoleByNprValue(
        ReadOnlySpan<char> vergeTjenesteoppgave,
        [NotNullWhen(true)] out ExternalRoleReference? role)
    {
        var s = vergeTjenesteoppgave;
        if (s.Length is < 8 or > 25)
        {
            goto end;
        }

        if (s.SequenceEqual("fastlege"))
        {
            role = GuardianshipRoles.Helfo.Fastlege;
            return true;
        }

        if (s.SequenceEqual("refusjonForPrivatpersoner"))
        {
            role = GuardianshipRoles.Helfo.RefusjonForPrivatpersoner;
            return true;
        }

        end:
        role = null;
        return false;
    }

    private static bool TryFindHelfoRoleByNprValue(
        ReadOnlySpan<byte> vergeTjenesteoppgave,
        [NotNullWhen(true)] out ExternalRoleReference? role)
    {
        var s = vergeTjenesteoppgave;
        if (s.Length is < 8 or > 25)
        {
            goto end;
        }

        if (s.SequenceEqual("fastlege"u8))
        {
            role = GuardianshipRoles.Helfo.Fastlege;
            return true;
        }

        if (s.SequenceEqual("refusjonForPrivatpersoner"u8))
        {
            role = GuardianshipRoles.Helfo.RefusjonForPrivatpersoner;
            return true;
        }

        end:
        role = null;
        return false;
    }

    private static bool TryFindHusbankenRoleByNprValue(
        ReadOnlySpan<char> vergeTjenesteoppgave,
        [NotNullWhen(true)] out ExternalRoleReference? role)
    {
        var s = vergeTjenesteoppgave;
        if (s.Length is < 9 or > 9)
        {
            goto end;
        }

        if (s.SequenceEqual("bostoette"))
        {
            role = GuardianshipRoles.Husbanken.Bostøtte;
            return true;
        }

        if (s.SequenceEqual("startlaan"))
        {
            role = GuardianshipRoles.Husbanken.Startlån;
            return true;
        }

        end:
        role = null;
        return false;
    }

    private static bool TryFindHusbankenRoleByNprValue(
        ReadOnlySpan<byte> vergeTjenesteoppgave,
        [NotNullWhen(true)] out ExternalRoleReference? role)
    {
        var s = vergeTjenesteoppgave;
        if (s.Length is < 9 or > 9)
        {
            goto end;
        }

        if (s.SequenceEqual("bostoette"u8))
        {
            role = GuardianshipRoles.Husbanken.Bostøtte;
            return true;
        }

        if (s.SequenceEqual("startlaan"u8))
        {
            role = GuardianshipRoles.Husbanken.Startlån;
            return true;
        }

        end:
        role = null;
        return false;
    }

    private static bool TryFindInkassoselskapRoleByNprValue(
        ReadOnlySpan<char> vergeTjenesteoppgave,
        [NotNullWhen(true)] out ExternalRoleReference? role)
    {
        var s = vergeTjenesteoppgave;
        if (s.SequenceEqual("forhandleOgInngaaInkassoavtaler"))
        {
            role = GuardianshipRoles.Inkassoselskap.ForhandleOgInngåInkassoavtaler;
            return true;
        }

        end:
        role = null;
        return false;
    }

    private static bool TryFindInkassoselskapRoleByNprValue(
        ReadOnlySpan<byte> vergeTjenesteoppgave,
        [NotNullWhen(true)] out ExternalRoleReference? role)
    {
        var s = vergeTjenesteoppgave;
        if (s.SequenceEqual("forhandleOgInngaaInkassoavtaler"u8))
        {
            role = GuardianshipRoles.Inkassoselskap.ForhandleOgInngåInkassoavtaler;
            return true;
        }

        end:
        role = null;
        return false;
    }

    private static bool TryFindKartverketRoleByNprValue(
        ReadOnlySpan<char> vergeTjenesteoppgave,
        [NotNullWhen(true)] out ExternalRoleReference? role)
    {
        var s = vergeTjenesteoppgave;
        if (s.Length is < 8 or > 33)
        {
            goto end;
        }

        if (s.StartsWith("s"))
        {
            var s_0 = s.Slice(1);
            if (s_0.Length is < 7 or > 32)
            {
                goto end;
            }

            if (s_0.SequenceEqual("letting"))
            {
                role = GuardianshipRoles.Kartverket.Sletting;
                return true;
            }

            if (s_0.SequenceEqual("algAvFastEiendomBorettslagsandel"))
            {
                role = GuardianshipRoles.Kartverket.SalgAvFastEiendomBorettslagsandel;
                return true;
            }

            goto end;
        }

        if (s.StartsWith("a"))
        {
            var s_1 = s.Slice(1);
            if (s_1.Length is < 19 or > 23)
            {
                goto end;
            }

            if (s_1.SequenceEqual("vtalerOgRettigheter"))
            {
                role = GuardianshipRoles.Kartverket.AvtalerOgRettigheter;
                return true;
            }

            if (s_1.SequenceEqual("rvPrivatSkifteOgUskifte"))
            {
                role = GuardianshipRoles.Kartverket.ArvPrivatSkifteOgUskifte;
                return true;
            }

            goto end;
        }

        if (s.SequenceEqual("laaneopptak"))
        {
            role = GuardianshipRoles.Kartverket.Låneopptak;
            return true;
        }

        if (s.SequenceEqual("kjoepAvEiendom"))
        {
            role = GuardianshipRoles.Kartverket.KjøpAvEiendom;
            return true;
        }

        if (s.SequenceEqual("endringAvEiendom"))
        {
            role = GuardianshipRoles.Kartverket.EndringAvEiendom;
            return true;
        }

        end:
        role = null;
        return false;
    }

    private static bool TryFindKartverketRoleByNprValue(
        ReadOnlySpan<byte> vergeTjenesteoppgave,
        [NotNullWhen(true)] out ExternalRoleReference? role)
    {
        var s = vergeTjenesteoppgave;
        if (s.Length is < 8 or > 33)
        {
            goto end;
        }

        if (s.StartsWith("s"u8))
        {
            var s_0 = s.Slice(1);
            if (s_0.Length is < 7 or > 32)
            {
                goto end;
            }

            if (s_0.SequenceEqual("letting"u8))
            {
                role = GuardianshipRoles.Kartverket.Sletting;
                return true;
            }

            if (s_0.SequenceEqual("algAvFastEiendomBorettslagsandel"u8))
            {
                role = GuardianshipRoles.Kartverket.SalgAvFastEiendomBorettslagsandel;
                return true;
            }

            goto end;
        }

        if (s.StartsWith("a"u8))
        {
            var s_1 = s.Slice(1);
            if (s_1.Length is < 19 or > 23)
            {
                goto end;
            }

            if (s_1.SequenceEqual("vtalerOgRettigheter"u8))
            {
                role = GuardianshipRoles.Kartverket.AvtalerOgRettigheter;
                return true;
            }

            if (s_1.SequenceEqual("rvPrivatSkifteOgUskifte"u8))
            {
                role = GuardianshipRoles.Kartverket.ArvPrivatSkifteOgUskifte;
                return true;
            }

            goto end;
        }

        if (s.SequenceEqual("laaneopptak"u8))
        {
            role = GuardianshipRoles.Kartverket.Låneopptak;
            return true;
        }

        if (s.SequenceEqual("kjoepAvEiendom"u8))
        {
            role = GuardianshipRoles.Kartverket.KjøpAvEiendom;
            return true;
        }

        if (s.SequenceEqual("endringAvEiendom"u8))
        {
            role = GuardianshipRoles.Kartverket.EndringAvEiendom;
            return true;
        }

        end:
        role = null;
        return false;
    }

    private static bool TryFindKommuneRoleByNprValue(
        ReadOnlySpan<char> vergeTjenesteoppgave,
        [NotNullWhen(true)] out ExternalRoleReference? role)
    {
        var s = vergeTjenesteoppgave;
        if (s.Length is < 13 or > 16)
        {
            goto end;
        }

        if (s.StartsWith("s"))
        {
            var s_0 = s.Slice(1);
            if (s_0.Length is < 12 or > 15)
            {
                goto end;
            }

            if (s_0.StartsWith("k"))
            {
                var s_0_0 = s_0.Slice(1);
                if (s_0_0.Length is < 11 or > 14)
                {
                    goto end;
                }

                if (s_0_0.SequenceEqual("attOgAvgift"))
                {
                    role = GuardianshipRoles.Kommune.SkattOgAvgift;
                    return true;
                }

                if (s_0_0.SequenceEqual("oleOgUtdanning"))
                {
                    role = GuardianshipRoles.Kommune.SkoleOgUtdanning;
                    return true;
                }

                goto end;
            }

            if (s_0.SequenceEqual("osialeTjenester"))
            {
                role = GuardianshipRoles.Kommune.SosialeTjenester;
                return true;
            }

            goto end;
        }

        if (s.SequenceEqual("byggOgEiendom"))
        {
            role = GuardianshipRoles.Kommune.ByggOgEiendom;
            return true;
        }

        if (s.SequenceEqual("helseOgOmsorg"))
        {
            role = GuardianshipRoles.Kommune.HelseOgOmsorg;
            return true;
        }

        end:
        role = null;
        return false;
    }

    private static bool TryFindKommuneRoleByNprValue(
        ReadOnlySpan<byte> vergeTjenesteoppgave,
        [NotNullWhen(true)] out ExternalRoleReference? role)
    {
        var s = vergeTjenesteoppgave;
        if (s.Length is < 13 or > 16)
        {
            goto end;
        }

        if (s.StartsWith("s"u8))
        {
            var s_0 = s.Slice(1);
            if (s_0.Length is < 12 or > 15)
            {
                goto end;
            }

            if (s_0.StartsWith("k"u8))
            {
                var s_0_0 = s_0.Slice(1);
                if (s_0_0.Length is < 11 or > 14)
                {
                    goto end;
                }

                if (s_0_0.SequenceEqual("attOgAvgift"u8))
                {
                    role = GuardianshipRoles.Kommune.SkattOgAvgift;
                    return true;
                }

                if (s_0_0.SequenceEqual("oleOgUtdanning"u8))
                {
                    role = GuardianshipRoles.Kommune.SkoleOgUtdanning;
                    return true;
                }

                goto end;
            }

            if (s_0.SequenceEqual("osialeTjenester"u8))
            {
                role = GuardianshipRoles.Kommune.SosialeTjenester;
                return true;
            }

            goto end;
        }

        if (s.SequenceEqual("byggOgEiendom"u8))
        {
            role = GuardianshipRoles.Kommune.ByggOgEiendom;
            return true;
        }

        if (s.SequenceEqual("helseOgOmsorg"u8))
        {
            role = GuardianshipRoles.Kommune.HelseOgOmsorg;
            return true;
        }

        end:
        role = null;
        return false;
    }

    private static bool TryFindKredittvurderingsselskapRoleByNprValue(
        ReadOnlySpan<char> vergeTjenesteoppgave,
        [NotNullWhen(true)] out ExternalRoleReference? role)
    {
        var s = vergeTjenesteoppgave;
        if (s.SequenceEqual("kredittsperre"))
        {
            role = GuardianshipRoles.Kredittvurderingsselskap.Kredittsperre;
            return true;
        }

        end:
        role = null;
        return false;
    }

    private static bool TryFindKredittvurderingsselskapRoleByNprValue(
        ReadOnlySpan<byte> vergeTjenesteoppgave,
        [NotNullWhen(true)] out ExternalRoleReference? role)
    {
        var s = vergeTjenesteoppgave;
        if (s.SequenceEqual("kredittsperre"u8))
        {
            role = GuardianshipRoles.Kredittvurderingsselskap.Kredittsperre;
            return true;
        }

        end:
        role = null;
        return false;
    }

    private static bool TryFindNamsmannenRoleByNprValue(
        ReadOnlySpan<char> vergeTjenesteoppgave,
        [NotNullWhen(true)] out ExternalRoleReference? role)
    {
        var s = vergeTjenesteoppgave;
        if (s.Length is < 13 or > 18)
        {
            goto end;
        }

        if (s.SequenceEqual("gjeldsordning"))
        {
            role = GuardianshipRoles.Namsmannen.Gjeldsordning;
            return true;
        }

        if (s.SequenceEqual("tvangsfullbyrdelse"))
        {
            role = GuardianshipRoles.Namsmannen.Tvangsfullbyrdelse;
            return true;
        }

        end:
        role = null;
        return false;
    }

    private static bool TryFindNamsmannenRoleByNprValue(
        ReadOnlySpan<byte> vergeTjenesteoppgave,
        [NotNullWhen(true)] out ExternalRoleReference? role)
    {
        var s = vergeTjenesteoppgave;
        if (s.Length is < 13 or > 18)
        {
            goto end;
        }

        if (s.SequenceEqual("gjeldsordning"u8))
        {
            role = GuardianshipRoles.Namsmannen.Gjeldsordning;
            return true;
        }

        if (s.SequenceEqual("tvangsfullbyrdelse"u8))
        {
            role = GuardianshipRoles.Namsmannen.Tvangsfullbyrdelse;
            return true;
        }

        end:
        role = null;
        return false;
    }

    private static bool TryFindNavRoleByNprValue(
        ReadOnlySpan<char> vergeTjenesteoppgave,
        [NotNullWhen(true)] out ExternalRoleReference? role)
    {
        var s = vergeTjenesteoppgave;
        if (s.Length is < 6 or > 16)
        {
            goto end;
        }

        if (s.SequenceEqual("arbeid"))
        {
            role = GuardianshipRoles.Nav.Arbeid;
            return true;
        }

        if (s.SequenceEqual("familie"))
        {
            role = GuardianshipRoles.Nav.Familie;
            return true;
        }

        if (s.SequenceEqual("pensjon"))
        {
            role = GuardianshipRoles.Nav.Pensjon;
            return true;
        }

        if (s.SequenceEqual("hjelpemidler"))
        {
            role = GuardianshipRoles.Nav.Hjelpemidler;
            return true;
        }

        if (s.SequenceEqual("sosialeTjenester"))
        {
            role = GuardianshipRoles.Nav.SosialeTjenester;
            return true;
        }

        end:
        role = null;
        return false;
    }

    private static bool TryFindNavRoleByNprValue(
        ReadOnlySpan<byte> vergeTjenesteoppgave,
        [NotNullWhen(true)] out ExternalRoleReference? role)
    {
        var s = vergeTjenesteoppgave;
        if (s.Length is < 6 or > 16)
        {
            goto end;
        }

        if (s.SequenceEqual("arbeid"u8))
        {
            role = GuardianshipRoles.Nav.Arbeid;
            return true;
        }

        if (s.SequenceEqual("familie"u8))
        {
            role = GuardianshipRoles.Nav.Familie;
            return true;
        }

        if (s.SequenceEqual("pensjon"u8))
        {
            role = GuardianshipRoles.Nav.Pensjon;
            return true;
        }

        if (s.SequenceEqual("hjelpemidler"u8))
        {
            role = GuardianshipRoles.Nav.Hjelpemidler;
            return true;
        }

        if (s.SequenceEqual("sosialeTjenester"u8))
        {
            role = GuardianshipRoles.Nav.SosialeTjenester;
            return true;
        }

        end:
        role = null;
        return false;
    }

    private static bool TryFindPasientreiserRoleByNprValue(
        ReadOnlySpan<char> vergeTjenesteoppgave,
        [NotNullWhen(true)] out ExternalRoleReference? role)
    {
        var s = vergeTjenesteoppgave;
        if (s.SequenceEqual("refusjonAvPasientreiser"))
        {
            role = GuardianshipRoles.Pasientreiser.RefusjonAvPasientreiser;
            return true;
        }

        end:
        role = null;
        return false;
    }

    private static bool TryFindPasientreiserRoleByNprValue(
        ReadOnlySpan<byte> vergeTjenesteoppgave,
        [NotNullWhen(true)] out ExternalRoleReference? role)
    {
        var s = vergeTjenesteoppgave;
        if (s.SequenceEqual("refusjonAvPasientreiser"u8))
        {
            role = GuardianshipRoles.Pasientreiser.RefusjonAvPasientreiser;
            return true;
        }

        end:
        role = null;
        return false;
    }

    private static bool TryFindSkatteetatenRoleByNprValue(
        ReadOnlySpan<char> vergeTjenesteoppgave,
        [NotNullWhen(true)] out ExternalRoleReference? role)
    {
        var s = vergeTjenesteoppgave;
        if (s.Length is < 5 or > 16)
        {
            goto end;
        }

        if (s.SequenceEqual("skatt"))
        {
            role = GuardianshipRoles.Skatteetaten.Skatt;
            return true;
        }

        if (s.SequenceEqual("innkreving"))
        {
            role = GuardianshipRoles.Skatteetaten.Innkreving;
            return true;
        }

        if (s.SequenceEqual("meldeFlytting"))
        {
            role = GuardianshipRoles.Skatteetaten.MeldeFlytting;
            return true;
        }

        if (s.SequenceEqual("endrePostadresse"))
        {
            role = GuardianshipRoles.Skatteetaten.EndrePostadresse;
            return true;
        }

        end:
        role = null;
        return false;
    }

    private static bool TryFindSkatteetatenRoleByNprValue(
        ReadOnlySpan<byte> vergeTjenesteoppgave,
        [NotNullWhen(true)] out ExternalRoleReference? role)
    {
        var s = vergeTjenesteoppgave;
        if (s.Length is < 5 or > 16)
        {
            goto end;
        }

        if (s.SequenceEqual("skatt"u8))
        {
            role = GuardianshipRoles.Skatteetaten.Skatt;
            return true;
        }

        if (s.SequenceEqual("innkreving"u8))
        {
            role = GuardianshipRoles.Skatteetaten.Innkreving;
            return true;
        }

        if (s.SequenceEqual("meldeFlytting"u8))
        {
            role = GuardianshipRoles.Skatteetaten.MeldeFlytting;
            return true;
        }

        if (s.SequenceEqual("endrePostadresse"u8))
        {
            role = GuardianshipRoles.Skatteetaten.EndrePostadresse;
            return true;
        }

        end:
        role = null;
        return false;
    }

    private static bool TryFindStatensInnkrevingssentralRoleByNprValue(
        ReadOnlySpan<char> vergeTjenesteoppgave,
        [NotNullWhen(true)] out ExternalRoleReference? role)
    {
        var s = vergeTjenesteoppgave;
        if (s.SequenceEqual("gjeldsordningOgBetalingsavtaler"))
        {
            role = GuardianshipRoles.StatensInnkrevingssentral.GjeldsordningOgBetalingsavtaler;
            return true;
        }

        end:
        role = null;
        return false;
    }

    private static bool TryFindStatensInnkrevingssentralRoleByNprValue(
        ReadOnlySpan<byte> vergeTjenesteoppgave,
        [NotNullWhen(true)] out ExternalRoleReference? role)
    {
        var s = vergeTjenesteoppgave;
        if (s.SequenceEqual("gjeldsordningOgBetalingsavtaler"u8))
        {
            role = GuardianshipRoles.StatensInnkrevingssentral.GjeldsordningOgBetalingsavtaler;
            return true;
        }

        end:
        role = null;
        return false;
    }

    private static bool TryFindStatsforvalterRoleByNprValue(
        ReadOnlySpan<char> vergeTjenesteoppgave,
        [NotNullWhen(true)] out ExternalRoleReference? role)
    {
        var s = vergeTjenesteoppgave;
        if (s.SequenceEqual("soekeOmSamtykkeTilDisposisjon"))
        {
            role = GuardianshipRoles.Statsforvalter.SøkeOmSamtykkeTilDisposisjon;
            return true;
        }

        end:
        role = null;
        return false;
    }

    private static bool TryFindStatsforvalterRoleByNprValue(
        ReadOnlySpan<byte> vergeTjenesteoppgave,
        [NotNullWhen(true)] out ExternalRoleReference? role)
    {
        var s = vergeTjenesteoppgave;
        if (s.SequenceEqual("soekeOmSamtykkeTilDisposisjon"u8))
        {
            role = GuardianshipRoles.Statsforvalter.SøkeOmSamtykkeTilDisposisjon;
            return true;
        }

        end:
        role = null;
        return false;
    }

    private static bool TryFindTingrettenRoleByNprValue(
        ReadOnlySpan<char> vergeTjenesteoppgave,
        [NotNullWhen(true)] out ExternalRoleReference? role)
    {
        var s = vergeTjenesteoppgave;
        if (s.Length is < 15 or > 25)
        {
            goto end;
        }

        if (s.StartsWith("begjaere"))
        {
            var s_0 = s.Slice(8);
            if (s_0.Length is < 7 or > 17)
            {
                goto end;
            }

            if (s_0.SequenceEqual("Uskifte"))
            {
                role = GuardianshipRoles.Tingretten.BegjæreUskifte;
                return true;
            }

            if (s_0.SequenceEqual("SkifteAvUskiftebo"))
            {
                role = GuardianshipRoles.Tingretten.BegjæreSkifteAvUskiftebo;
                return true;
            }

            goto end;
        }

        if (s.SequenceEqual("privatSkifteAvDodsbo"))
        {
            role = GuardianshipRoles.Tingretten.PrivatSkifteAvDødsbo;
            return true;
        }

        end:
        role = null;
        return false;
    }

    private static bool TryFindTingrettenRoleByNprValue(
        ReadOnlySpan<byte> vergeTjenesteoppgave,
        [NotNullWhen(true)] out ExternalRoleReference? role)
    {
        var s = vergeTjenesteoppgave;
        if (s.Length is < 15 or > 25)
        {
            goto end;
        }

        if (s.StartsWith("begjaere"u8))
        {
            var s_0 = s.Slice(8);
            if (s_0.Length is < 7 or > 17)
            {
                goto end;
            }

            if (s_0.SequenceEqual("Uskifte"u8))
            {
                role = GuardianshipRoles.Tingretten.BegjæreUskifte;
                return true;
            }

            if (s_0.SequenceEqual("SkifteAvUskiftebo"u8))
            {
                role = GuardianshipRoles.Tingretten.BegjæreSkifteAvUskiftebo;
                return true;
            }

            goto end;
        }

        if (s.SequenceEqual("privatSkifteAvDodsbo"u8))
        {
            role = GuardianshipRoles.Tingretten.PrivatSkifteAvDødsbo;
            return true;
        }

        end:
        role = null;
        return false;
    }

    private static bool TryFindØvrigeRoleByNprValue(
        ReadOnlySpan<char> vergeTjenesteoppgave,
        [NotNullWhen(true)] out ExternalRoleReference? role)
    {
        var s = vergeTjenesteoppgave;
        if (s.Length is < 27 or > 36)
        {
            goto end;
        }

        if (s.SequenceEqual("kjoepLeieAvVarerOgTjenester"))
        {
            role = GuardianshipRoles.Øvrige.KjøpLeieAvVarerOgTjenester;
            return true;
        }

        if (s.SequenceEqual("salgAvLoesoereAvStoerreVerdi"))
        {
            role = GuardianshipRoles.Øvrige.SalgAvLøsøreAvStørreVerdi;
            return true;
        }

        if (s.SequenceEqual("inngaaelseAvHusleiekontrakter"))
        {
            role = GuardianshipRoles.Øvrige.InngåelseAvHusleiekontrakter;
            return true;
        }

        if (s.SequenceEqual("avslutningAvHusleiekontrakter"))
        {
            role = GuardianshipRoles.Øvrige.AvslutningAvHusleiekontrakter;
            return true;
        }

        if (s.SequenceEqual("disponereInntekterTilAaDekkeUtgifter"))
        {
            role = GuardianshipRoles.Øvrige.DisponereInntekterTilÅDekkeUtgifter;
            return true;
        }

        end:
        role = null;
        return false;
    }

    private static bool TryFindØvrigeRoleByNprValue(
        ReadOnlySpan<byte> vergeTjenesteoppgave,
        [NotNullWhen(true)] out ExternalRoleReference? role)
    {
        var s = vergeTjenesteoppgave;
        if (s.Length is < 27 or > 36)
        {
            goto end;
        }

        if (s.SequenceEqual("kjoepLeieAvVarerOgTjenester"u8))
        {
            role = GuardianshipRoles.Øvrige.KjøpLeieAvVarerOgTjenester;
            return true;
        }

        if (s.SequenceEqual("salgAvLoesoereAvStoerreVerdi"u8))
        {
            role = GuardianshipRoles.Øvrige.SalgAvLøsøreAvStørreVerdi;
            return true;
        }

        if (s.SequenceEqual("inngaaelseAvHusleiekontrakter"u8))
        {
            role = GuardianshipRoles.Øvrige.InngåelseAvHusleiekontrakter;
            return true;
        }

        if (s.SequenceEqual("avslutningAvHusleiekontrakter"u8))
        {
            role = GuardianshipRoles.Øvrige.AvslutningAvHusleiekontrakter;
            return true;
        }

        if (s.SequenceEqual("disponereInntekterTilAaDekkeUtgifter"u8))
        {
            role = GuardianshipRoles.Øvrige.DisponereInntekterTilÅDekkeUtgifter;
            return true;
        }

        end:
        role = null;
        return false;
    }
#pragma warning restore CS0164 // Unreferenced label
}
