// This file is autogenerated. Do not edit directly.
#nullable enable

using Altinn.Register.Contracts;
using Altinn.Register.Contracts.ExternalRoles;
using System.Diagnostics.CodeAnalysis;

namespace Altinn.Register.PartyImport.Npr;

/// <summary>Roles for guardianships.</summary>
internal static partial class GuardianshipRoles
{
    /// <summary>Roles for guardianships in the area 'Bank'.</summary>
    public static partial class Bank
    {
        /// <summary>Omfatter oppgaver knyttet til å opprette kundeforhold, opprette/avslutte konto, disposisjonsrett, etablere/endre betalingsavtaler og forvalte låneavtaler</summary>
        public static ExternalRoleReference RepresentasjonDagligbank { get; } = new(ExternalRoleSource.CivilRightsAuthority, "bank-representasjon-dagligbank");

        /// <summary>Gjelder søknad om etablering av banklån - dette krever statsforvalterens samtykke</summary>
        public static ExternalRoleReference TaOppLånKreditter { get; } = new(ExternalRoleSource.CivilRightsAuthority, "bank-ta-opp-lan-kreditter");
    }

    /// <summary>Roles for guardianships in the area 'Forsikringsselskap'.</summary>
    public static partial class Forsikringsselskap
    {
        /// <summary>Omfatter oppgaver knyttet til å etablere/endre/avslutte forsikringsavtaler og representasjon ved forsikringsoppgjør</summary>
        public static ExternalRoleReference ForvalteForsikringsavtaler { get; } = new(ExternalRoleSource.CivilRightsAuthority, "forsikringsselskap-forvalte-forsikringsavtaler");
    }

    /// <summary>Roles for guardianships in the area 'Helfo'.</summary>
    public static partial class Helfo
    {
        /// <summary>Gjelder bistand til å søke om stønad til helsetjenester etter folketrygdloven, herunder innsyn i og håndtering av egenandel-/frikortordningen og helsetjenester gitt i utlandet. Gjelder også når en tredjepart sender søknad på vegne av en person (eks. lege, arbeidsgiver, forsikringsselskap)</summary>
        public static ExternalRoleReference RefusjonForPrivatpersoner { get; } = new(ExternalRoleSource.CivilRightsAuthority, "helfo-refusjon-privatpersoner");

        /// <summary>Gjelder bistand til å bytte fastlege, samt å kunne se tidligere og nåværende fastlege</summary>
        public static ExternalRoleReference Fastlege { get; } = new(ExternalRoleSource.CivilRightsAuthority, "helfo-fastlege");
    }

    /// <summary>Roles for guardianships in the area 'Husbanken'.</summary>
    public static partial class Husbanken
    {
        /// <summary>Gjelder søknad om og/eller eventuelt klage på vedtak om statlig bostøtte hos Husbanken</summary>
        public static ExternalRoleReference Bostøtte { get; } = new(ExternalRoleSource.CivilRightsAuthority, "husbanken-bostotte");

        /// <summary>Gjelder søknad om og/eller eventuelt klage på vedtak om startlån hos Husbanken</summary>
        public static ExternalRoleReference Startlån { get; } = new(ExternalRoleSource.CivilRightsAuthority, "husbanken-startlan");
    }

    /// <summary>Roles for guardianships in the area 'Inkassoselskap'.</summary>
    public static partial class Inkassoselskap
    {
        /// <summary>Gjelder avtaleinngåelse og forhandling med ulike inkassoselskaper</summary>
        public static ExternalRoleReference ForhandleOgInngåInkassoavtaler { get; } = new(ExternalRoleSource.CivilRightsAuthority, "inkassoselskap-inkassoavtaler");
    }

    /// <summary>Roles for guardianships in the area 'Kartverket'.</summary>
    public static partial class Kartverket
    {
        /// <summary>Omfatter emnene tinglyse eierskifte, sletting av rettighet/servitutt/heftelse, sikringspant. Tjenesteområdet vil også gjelde for overføring av fast eiendom/borettslagsandel mellom ektefeller/samboere - dette krever statsforvalterens samtykke</summary>
        public static ExternalRoleReference SalgAvFastEiendomBorettslagsandel { get; } = new(ExternalRoleSource.CivilRightsAuthority, "kartverket-salg-fast-eiendom-borettslagsandel");

        /// <summary>Omfatter emnene tinglyse eierskifte, pantsette eiendom, tinglyse avtaler (rettighet/servitutt/heftelse) og festekontrakt - dette krever statsforvalterens samtykke</summary>
        public static ExternalRoleReference KjøpAvEiendom { get; } = new(ExternalRoleSource.CivilRightsAuthority, "kartverket-kjop-eiendom");

        /// <summary>Omfatter emnene hjemmelserklæring og skjøte videre - dette krever statsforvalterens samtykke</summary>
        public static ExternalRoleReference ArvPrivatSkifteOgUskifte { get; } = new(ExternalRoleSource.CivilRightsAuthority, "kartverket-arv-privat-skifte-uskifte");

        /// <summary>Omfatter emnene seksjonering, reseksjonering, fradelinger, sammenslåinger, registreringer av festegrunn, endringer av festenummer til bruksnummer, arealoverføring - dette krever statsforvalterens samtykke</summary>
        public static ExternalRoleReference EndringAvEiendom { get; } = new(ExternalRoleSource.CivilRightsAuthority, "kartverket-endring-eiendom");

        /// <summary>Omfatter emnene tinglyse avtaler (rettighet/servitutt/heftelse) og festekontrakt, tinglysning av prioritetsbestemmelser, nedkvitteringer, tinglysing på ny, transport av frivillige heftelser og tvangsforretninger, massetransport - dette krever statsforvalterens samtykke</summary>
        public static ExternalRoleReference AvtalerOgRettigheter { get; } = new(ExternalRoleSource.CivilRightsAuthority, "kartverket-avtaler-rettigheter");

        /// <summary>Gjelder sletting av rettigheter i fast eiendom - dette krever statsforvalterens samtykke</summary>
        public static ExternalRoleReference Sletting { get; } = new(ExternalRoleSource.CivilRightsAuthority, "kartverket-sletting");

        /// <summary>Omfatter emnene pantsette eiendom, refinansiering - dette krever statsforvalterens samtykke</summary>
        public static ExternalRoleReference Låneopptak { get; } = new(ExternalRoleSource.CivilRightsAuthority, "kartverket-laneopptak");
    }

    /// <summary>Roles for guardianships in the area 'Kommune'.</summary>
    public static partial class Kommune
    {
        /// <summary>Omfatter oppgaver som hører inn under områdene bygging, eiendom, kjøp og salg, leie og utleie, samt priser og gebyr for bygg og eiendom</summary>
        public static ExternalRoleReference ByggOgEiendom { get; } = new(ExternalRoleSource.CivilRightsAuthority, "kommune-bygg-eiendom");

        /// <summary>Omfatter tilbud og støtteordninger som hører inn under områdene avlastning og støtte, helsetjenester, omsorgstjenester og velferdsstøtte</summary>
        public static ExternalRoleReference HelseOgOmsorg { get; } = new(ExternalRoleSource.CivilRightsAuthority, "kommune-helse-omsorg");

        /// <summary>Omfatter oppgaver som hører inn under områdene arbeidsgiveravgift, kommunale avgifter, eiendomsskatt og skatteattest</summary>
        public static ExternalRoleReference SkattOgAvgift { get; } = new(ExternalRoleSource.CivilRightsAuthority, "kommune-skatt-avgift");

        /// <summary>Omfatter tilbud og støtteordninger som hører inn under områdene botilbud, kvalifisering til arbeid, økonomiske ytelser og rådgivning</summary>
        public static ExternalRoleReference SosialeTjenester { get; } = new(ExternalRoleSource.CivilRightsAuthority, "kommune-sosiale-tjenester");

        /// <summary>Omfatter tilbud og støtteordninger som hører inn under områdene grunnskole, videregående skole, høyere utdanning, voksenopplæring og skolehverdag</summary>
        public static ExternalRoleReference SkoleOgUtdanning { get; } = new(ExternalRoleSource.CivilRightsAuthority, "kommune-skole-utdanning");
    }

    /// <summary>Roles for guardianships in the area 'Kredittvurderingsselskap'.</summary>
    public static partial class Kredittvurderingsselskap
    {
        /// <summary>Gjelder avtaleinngåelse om kredittsperre</summary>
        public static ExternalRoleReference Kredittsperre { get; } = new(ExternalRoleSource.CivilRightsAuthority, "kredittvurderingsselskap-kredittsperre");
    }

    /// <summary>Roles for guardianships in the area 'Namsmannen'.</summary>
    public static partial class Namsmannen
    {
        /// <summary>Gjelder søknad om og/eller forvaltning av eksisterende gjeldsordninger</summary>
        public static ExternalRoleReference Gjeldsordning { get; } = new(ExternalRoleSource.CivilRightsAuthority, "namsmannen-gjeldsordning");

        /// <summary>Gjelder representasjon i saker om tvangsfullbyrdelse etter tvangsfullbyrdelsesloven</summary>
        public static ExternalRoleReference Tvangsfullbyrdelse { get; } = new(ExternalRoleSource.CivilRightsAuthority, "namsmannen-tvangsfullbyrdelse");
    }

    /// <summary>Roles for guardianships in the area 'Nav'.</summary>
    public static partial class Nav
    {
        /// <summary>Omfatter tilbud og støtteordninger som hører inn under områdene forsikring/sykepenger (selvstendig næringsdrivende og frilansere), sykepenger, tilleggsstønad og yrkesskade/menerstatning og arbeidsavklaringspenger. Gjelder innsyn/saksbehandling og utbetaling</summary>
        public static ExternalRoleReference Arbeid { get; } = new(ExternalRoleSource.CivilRightsAuthority, "nav-arbeid");

        /// <summary>Omfatter tilbud og støtteordninger som hører inn under områdene barnebidrag, barnetrygd, enslig forsørger, foreldre- og svangerskapspenger, grunn- og hjelpestønad og kontantstøtte. Gjelder innsyn/saksbehandling og utbetaling</summary>
        public static ExternalRoleReference Familie { get; } = new(ExternalRoleSource.CivilRightsAuthority, "nav-familie");

        /// <summary>Omfatter emnene hjelpemidler, helsetjenester, ortopediske hjelpemidler og bil</summary>
        public static ExternalRoleReference Hjelpemidler { get; } = new(ExternalRoleSource.CivilRightsAuthority, "nav-hjelpemidler");

        /// <summary>Omfatter tilbud og støtteordninger som hører inn under områdene alderspensjon, supplerende stønad, uførepensjon/-trygd, avtalefestet pensjon, ytelser for gjenlevende (alle typer pensjonsytelser). Gjelder innsyn/saksbehandling og utbetaling</summary>
        public static ExternalRoleReference Pensjon { get; } = new(ExternalRoleSource.CivilRightsAuthority, "nav-pensjon");

        /// <summary>Omfatter tilbud og støtteordninger som hører inn under områdene gjeldsrådgivning, kvalifiseringsprogrammet, midlertidig botilbud, økonomisk rådgivning, forsvarlig livsopphold, midlertidig inntektssikring og økonomisk stønad. Gjelder innsyn/saksbehandling og utbetaling</summary>
        public static ExternalRoleReference SosialeTjenester { get; } = new(ExternalRoleSource.CivilRightsAuthority, "nav-sosiale-tjenester");
    }

    /// <summary>Roles for guardianships in the area 'Pasientreiser'.</summary>
    public static partial class Pasientreiser
    {
        /// <summary>Søknad om og/eller eventuell klage på vedtak om refusjon av reiseutgifter i forbindelse med behandlinger som dekkes av det offentlige</summary>
        public static ExternalRoleReference RefusjonAvPasientreiser { get; } = new(ExternalRoleSource.CivilRightsAuthority, "pasientreiser-refusjon-pasientreiser");
    }

    /// <summary>Roles for guardianships in the area 'Skatteetaten'.</summary>
    public static partial class Skatteetaten
    {
        /// <summary>Gjelder oppfølging og behandling av krav fra Skatteetaten, for eksempel restskatt</summary>
        public static ExternalRoleReference Innkreving { get; } = new(ExternalRoleSource.CivilRightsAuthority, "skatteetaten-innkreving");

        /// <summary>Gjelder endring av postadresse for person med verge</summary>
        public static ExternalRoleReference EndrePostadresse { get; } = new(ExternalRoleSource.CivilRightsAuthority, "skatteetaten-endre-postadresse");

        /// <summary>Gjelder endring av bostedsadresse</summary>
        public static ExternalRoleReference MeldeFlytting { get; } = new(ExternalRoleSource.CivilRightsAuthority, "skatteetaten-melde-flytting");

        /// <summary>Gjelder innsyn i skattedata, og representasjon overfor skattemyndighetene i alle saker om skatteforhold, herunder endring av skattekort, levering av skattemelding, skatteoppgjør og det ordinære løpet for restskatt eller penger til gode.</summary>
        public static ExternalRoleReference Skatt { get; } = new(ExternalRoleSource.CivilRightsAuthority, "skatteetaten-skatt");
    }

    /// <summary>Roles for guardianships in the area 'Statens innkrevingssentral'.</summary>
    public static partial class StatensInnkrevingssentral
    {
        /// <summary>Gjelder søknad om og forvaltning av gjeldsordning og betalingsavtaler</summary>
        public static ExternalRoleReference GjeldsordningOgBetalingsavtaler { get; } = new(ExternalRoleSource.CivilRightsAuthority, "statens-innkrevingssentral-gjeldsordning-betalingsavtaler");
    }

    /// <summary>Roles for guardianships in the area 'Statsforvalter'.</summary>
    public static partial class Statsforvalter
    {
        /// <summary>Gjelder søknad om disposisjoner som krever statsforvalterens samtykke</summary>
        public static ExternalRoleReference SøkeOmSamtykkeTilDisposisjon { get; } = new(ExternalRoleSource.CivilRightsAuthority, "statsforvalter-soke-om-samtykke-disposisjon");
    }

    /// <summary>Roles for guardianships in the area 'Tingretten'.</summary>
    public static partial class Tingretten
    {
        /// <summary>Gjelder melding om uskiftet bo jf. vgml. § 41 (3) og arvl. §§ 14 og 32 - dette krever statsforvalterens samtykke</summary>
        public static ExternalRoleReference BegjæreUskifte { get; } = new(ExternalRoleSource.CivilRightsAuthority, "tingretten-begjaere-uskifte");

        /// <summary>Omfatter tilfeller der vergen på vegne av vergehaveren overtar boet til privat skifte og ivaretakelse av andre rettigheter som arving</summary>
        public static ExternalRoleReference PrivatSkifteAvDødsbo { get; } = new(ExternalRoleSource.CivilRightsAuthority, "tingretten-privat-skifte-dodsbo");

        /// <summary>Gjelder skifte av uskiftebo jf. vgml. § 41 (3) og arvl. §§ 28 og 29 - dette krever statsforvalterens samtykke</summary>
        public static ExternalRoleReference BegjæreSkifteAvUskiftebo { get; } = new(ExternalRoleSource.CivilRightsAuthority, "tingretten-begjaere-skifte-uskiftebo");
    }

    /// <summary>Roles for guardianships in the area 'Øvrige'.</summary>
    public static partial class Øvrige
    {
        /// <summary>Gjelder i forbindelse med kjøp av varer og tjenester, omfatter også heving av avtaler, reklamasjon mm.</summary>
        public static ExternalRoleReference KjøpLeieAvVarerOgTjenester { get; } = new(ExternalRoleSource.CivilRightsAuthority, "ovrige-kjop-leie-varer-tjenester");

        /// <summary>Gjelder i forbindelse med inngåelse av husleiekontrakter</summary>
        public static ExternalRoleReference InngåelseAvHusleiekontrakter { get; } = new(ExternalRoleSource.CivilRightsAuthority, "ovrige-inngaelse-husleiekontrakter");

        /// <summary>Gjelder i forbindelse med avslutning av husleiekontrakter</summary>
        public static ExternalRoleReference AvslutningAvHusleiekontrakter { get; } = new(ExternalRoleSource.CivilRightsAuthority, "ovrige-avslutning-husleiekontrakter");

        /// <summary>Gjelder salg av løsøre av større verdi (herunder bil), usedvanlig karakter eller av spesiell interesse for vergehaver eller dennes nærmeste familie - dette krever statsforvalterens samtykke</summary>
        public static ExternalRoleReference SalgAvLøsøreAvStørreVerdi { get; } = new(ExternalRoleSource.CivilRightsAuthority, "ovrige-salg-losore-storre-verdi");

        /// <summary>Gjelder adgangen til å bruke vergehaverens inntekter til å betale regninger, betjene gjeld, og dekke øvrige utgifter</summary>
        public static ExternalRoleReference DisponereInntekterTilÅDekkeUtgifter { get; } = new(ExternalRoleSource.CivilRightsAuthority, "ovrige-disponere-inntekter-dekke-utgifter");
    }
}

/// <summary>Mappings of guardianship values from npr to Altinn Register.</summary>
internal static partial class GuardianshipRoleMapper
{
    /// <summary>Tries to find a guardianship role by NPR values.</summary>
    /// <param name="vergeTjenestevirksomhet">The NPR value for the guardianship area.</param>
    /// <param name="vergeTjenesteoppgave">The NPR value for the guardianship task.</param>
    /// <param name="role">The found role, if any.</param>
    /// <returns><see langword="true"/> if a role was found; otherwise, <see langword="false"/>.</returns>
    public static bool TryFindRoleByNprValues(
        ReadOnlySpan<char> vergeTjenestevirksomhet,
        ReadOnlySpan<char> vergeTjenesteoppgave,
        [NotNullWhen(true)] out ExternalRoleReference? role)
    {
        var s = vergeTjenestevirksomhet;
        if (s.StartsWith("h"))
        {
            var s_0 = s.Slice(1);
            if (s_0.StartsWith("elfo"))
            {
                var s_0_0 = s_0.Slice(4);
                if (s_0_0.Length == 0)
                {
                    return TryFindHelfoRoleByNprValue(vergeTjenesteoppgave, out role);
                }
                else
                {
                    goto end;
                }
            }

            if (s_0.StartsWith("usbanken"))
            {
                var s_0_1 = s_0.Slice(8);
                if (s_0_1.Length == 0)
                {
                    return TryFindHusbankenRoleByNprValue(vergeTjenesteoppgave, out role);
                }
                else
                {
                    goto end;
                }
            }
        }

        if (s.StartsWith("k"))
        {
            var s_1 = s.Slice(1);
            if (s_1.StartsWith("ommune"))
            {
                var s_1_0 = s_1.Slice(6);
                if (s_1_0.Length == 0)
                {
                    return TryFindKommuneRoleByNprValue(vergeTjenesteoppgave, out role);
                }
                else
                {
                    goto end;
                }
            }

            if (s_1.StartsWith("artverket"))
            {
                var s_1_1 = s_1.Slice(9);
                if (s_1_1.Length == 0)
                {
                    return TryFindKartverketRoleByNprValue(vergeTjenesteoppgave, out role);
                }
                else
                {
                    goto end;
                }
            }

            if (s_1.StartsWith("redittvurderingsselskap"))
            {
                var s_1_2 = s_1.Slice(23);
                if (s_1_2.Length == 0)
                {
                    return TryFindKredittvurderingsselskapRoleByNprValue(vergeTjenesteoppgave, out role);
                }
                else
                {
                    goto end;
                }
            }
        }

        if (s.StartsWith("s"))
        {
            var s_2 = s.Slice(1);
            if (s_2.StartsWith("tat"))
            {
                var s_2_0 = s_2.Slice(3);
                if (s_2_0.StartsWith("sforvalter"))
                {
                    var s_2_0_0 = s_2_0.Slice(10);
                    if (s_2_0_0.Length == 0)
                    {
                        return TryFindStatsforvalterRoleByNprValue(vergeTjenesteoppgave, out role);
                    }
                    else
                    {
                        goto end;
                    }
                }

                if (s_2_0.StartsWith("ensInnkrevingssentral"))
                {
                    var s_2_0_1 = s_2_0.Slice(21);
                    if (s_2_0_1.Length == 0)
                    {
                        return TryFindStatensInnkrevingssentralRoleByNprValue(vergeTjenesteoppgave, out role);
                    }
                    else
                    {
                        goto end;
                    }
                }
            }

            if (s_2.StartsWith("katteetaten"))
            {
                var s_2_1 = s_2.Slice(11);
                if (s_2_1.Length == 0)
                {
                    return TryFindSkatteetatenRoleByNprValue(vergeTjenesteoppgave, out role);
                }
                else
                {
                    goto end;
                }
            }
        }

        if (s.StartsWith("na"))
        {
            var s_3 = s.Slice(2);
            if (s_3.StartsWith("v"))
            {
                var s_3_0 = s_3.Slice(1);
                if (s_3_0.Length == 0)
                {
                    return TryFindNavRoleByNprValue(vergeTjenesteoppgave, out role);
                }
                else
                {
                    goto end;
                }
            }

            if (s_3.StartsWith("msmannen"))
            {
                var s_3_1 = s_3.Slice(8);
                if (s_3_1.Length == 0)
                {
                    return TryFindNamsmannenRoleByNprValue(vergeTjenesteoppgave, out role);
                }
                else
                {
                    goto end;
                }
            }
        }

        if (s.StartsWith("bank"))
        {
            var s_4 = s.Slice(4);
            if (s_4.Length == 0)
            {
                return TryFindBankRoleByNprValue(vergeTjenesteoppgave, out role);
            }
            else
            {
                goto end;
            }
        }

        if (s.StartsWith("oevrige"))
        {
            var s_5 = s.Slice(7);
            if (s_5.Length == 0)
            {
                return TryFindØvrigeRoleByNprValue(vergeTjenesteoppgave, out role);
            }
            else
            {
                goto end;
            }
        }

        if (s.StartsWith("tingretten"))
        {
            var s_6 = s.Slice(10);
            if (s_6.Length == 0)
            {
                return TryFindTingrettenRoleByNprValue(vergeTjenesteoppgave, out role);
            }
            else
            {
                goto end;
            }
        }

        if (s.StartsWith("pasientreiser"))
        {
            var s_7 = s.Slice(13);
            if (s_7.Length == 0)
            {
                return TryFindPasientreiserRoleByNprValue(vergeTjenesteoppgave, out role);
            }
            else
            {
                goto end;
            }
        }

        if (s.StartsWith("inkassoselskap"))
        {
            var s_8 = s.Slice(14);
            if (s_8.Length == 0)
            {
                return TryFindInkassoselskapRoleByNprValue(vergeTjenesteoppgave, out role);
            }
            else
            {
                goto end;
            }
        }

        if (s.StartsWith("forsikringsselskap"))
        {
            var s_9 = s.Slice(18);
            if (s_9.Length == 0)
            {
                return TryFindForsikringsselskapRoleByNprValue(vergeTjenesteoppgave, out role);
            }
            else
            {
                goto end;
            }
        }

        end:
        role = null;
        return false;
    }

    /// <summary>Tries to find a guardianship role by NPR values.</summary>
    /// <param name="vergeTjenestevirksomhet">The NPR value for the guardianship area.</param>
    /// <param name="vergeTjenesteoppgave">The NPR value for the guardianship task.</param>
    /// <param name="role">The found role, if any.</param>
    /// <returns><see langword="true"/> if a role was found; otherwise, <see langword="false"/>.</returns>
    public static bool TryFindRoleByNprValues(
        ReadOnlySpan<byte> vergeTjenestevirksomhet,
        ReadOnlySpan<byte> vergeTjenesteoppgave,
        [NotNullWhen(true)] out ExternalRoleReference? role)
    {
        var s = vergeTjenestevirksomhet;
        if (s.StartsWith("h"u8))
        {
            var s_0 = s.Slice(1);
            if (s_0.StartsWith("elfo"u8))
            {
                var s_0_0 = s_0.Slice(4);
                if (s_0_0.Length == 0)
                {
                    return TryFindHelfoRoleByNprValue(vergeTjenesteoppgave, out role);
                }
                else
                {
                    goto end;
                }
            }

            if (s_0.StartsWith("usbanken"u8))
            {
                var s_0_1 = s_0.Slice(8);
                if (s_0_1.Length == 0)
                {
                    return TryFindHusbankenRoleByNprValue(vergeTjenesteoppgave, out role);
                }
                else
                {
                    goto end;
                }
            }
        }

        if (s.StartsWith("k"u8))
        {
            var s_1 = s.Slice(1);
            if (s_1.StartsWith("ommune"u8))
            {
                var s_1_0 = s_1.Slice(6);
                if (s_1_0.Length == 0)
                {
                    return TryFindKommuneRoleByNprValue(vergeTjenesteoppgave, out role);
                }
                else
                {
                    goto end;
                }
            }

            if (s_1.StartsWith("artverket"u8))
            {
                var s_1_1 = s_1.Slice(9);
                if (s_1_1.Length == 0)
                {
                    return TryFindKartverketRoleByNprValue(vergeTjenesteoppgave, out role);
                }
                else
                {
                    goto end;
                }
            }

            if (s_1.StartsWith("redittvurderingsselskap"u8))
            {
                var s_1_2 = s_1.Slice(23);
                if (s_1_2.Length == 0)
                {
                    return TryFindKredittvurderingsselskapRoleByNprValue(vergeTjenesteoppgave, out role);
                }
                else
                {
                    goto end;
                }
            }
        }

        if (s.StartsWith("s"u8))
        {
            var s_2 = s.Slice(1);
            if (s_2.StartsWith("tat"u8))
            {
                var s_2_0 = s_2.Slice(3);
                if (s_2_0.StartsWith("sforvalter"u8))
                {
                    var s_2_0_0 = s_2_0.Slice(10);
                    if (s_2_0_0.Length == 0)
                    {
                        return TryFindStatsforvalterRoleByNprValue(vergeTjenesteoppgave, out role);
                    }
                    else
                    {
                        goto end;
                    }
                }

                if (s_2_0.StartsWith("ensInnkrevingssentral"u8))
                {
                    var s_2_0_1 = s_2_0.Slice(21);
                    if (s_2_0_1.Length == 0)
                    {
                        return TryFindStatensInnkrevingssentralRoleByNprValue(vergeTjenesteoppgave, out role);
                    }
                    else
                    {
                        goto end;
                    }
                }
            }

            if (s_2.StartsWith("katteetaten"u8))
            {
                var s_2_1 = s_2.Slice(11);
                if (s_2_1.Length == 0)
                {
                    return TryFindSkatteetatenRoleByNprValue(vergeTjenesteoppgave, out role);
                }
                else
                {
                    goto end;
                }
            }
        }

        if (s.StartsWith("na"u8))
        {
            var s_3 = s.Slice(2);
            if (s_3.StartsWith("v"u8))
            {
                var s_3_0 = s_3.Slice(1);
                if (s_3_0.Length == 0)
                {
                    return TryFindNavRoleByNprValue(vergeTjenesteoppgave, out role);
                }
                else
                {
                    goto end;
                }
            }

            if (s_3.StartsWith("msmannen"u8))
            {
                var s_3_1 = s_3.Slice(8);
                if (s_3_1.Length == 0)
                {
                    return TryFindNamsmannenRoleByNprValue(vergeTjenesteoppgave, out role);
                }
                else
                {
                    goto end;
                }
            }
        }

        if (s.StartsWith("bank"u8))
        {
            var s_4 = s.Slice(4);
            if (s_4.Length == 0)
            {
                return TryFindBankRoleByNprValue(vergeTjenesteoppgave, out role);
            }
            else
            {
                goto end;
            }
        }

        if (s.StartsWith("oevrige"u8))
        {
            var s_5 = s.Slice(7);
            if (s_5.Length == 0)
            {
                return TryFindØvrigeRoleByNprValue(vergeTjenesteoppgave, out role);
            }
            else
            {
                goto end;
            }
        }

        if (s.StartsWith("tingretten"u8))
        {
            var s_6 = s.Slice(10);
            if (s_6.Length == 0)
            {
                return TryFindTingrettenRoleByNprValue(vergeTjenesteoppgave, out role);
            }
            else
            {
                goto end;
            }
        }

        if (s.StartsWith("pasientreiser"u8))
        {
            var s_7 = s.Slice(13);
            if (s_7.Length == 0)
            {
                return TryFindPasientreiserRoleByNprValue(vergeTjenesteoppgave, out role);
            }
            else
            {
                goto end;
            }
        }

        if (s.StartsWith("inkassoselskap"u8))
        {
            var s_8 = s.Slice(14);
            if (s_8.Length == 0)
            {
                return TryFindInkassoselskapRoleByNprValue(vergeTjenesteoppgave, out role);
            }
            else
            {
                goto end;
            }
        }

        if (s.StartsWith("forsikringsselskap"u8))
        {
            var s_9 = s.Slice(18);
            if (s_9.Length == 0)
            {
                return TryFindForsikringsselskapRoleByNprValue(vergeTjenesteoppgave, out role);
            }
            else
            {
                goto end;
            }
        }

        end:
        role = null;
        return false;
    }

    private static bool TryFindBankRoleByNprValue(
        ReadOnlySpan<char> vergeTjenesteoppgave,
        [NotNullWhen(true)] out ExternalRoleReference? role)
    {
        var s = vergeTjenesteoppgave;
        if (s.StartsWith("taOppLaanKreditter"))
        {
            var s_0 = s.Slice(18);
            if (s_0.Length == 0)
            {
                role = GuardianshipRoles.Bank.TaOppLånKreditter;
                return true;
            }
            else
            {
                goto end;
            }
        }

        if (s.StartsWith("representasjonDagligbank"))
        {
            var s_1 = s.Slice(24);
            if (s_1.Length == 0)
            {
                role = GuardianshipRoles.Bank.RepresentasjonDagligbank;
                return true;
            }
            else
            {
                goto end;
            }
        }

        end:
        role = null;
        return false;
    }

    private static bool TryFindBankRoleByNprValue(
        ReadOnlySpan<byte> vergeTjenesteoppgave,
        [NotNullWhen(true)] out ExternalRoleReference? role)
    {
        var s = vergeTjenesteoppgave;
        if (s.StartsWith("taOppLaanKreditter"u8))
        {
            var s_0 = s.Slice(18);
            if (s_0.Length == 0)
            {
                role = GuardianshipRoles.Bank.TaOppLånKreditter;
                return true;
            }
            else
            {
                goto end;
            }
        }

        if (s.StartsWith("representasjonDagligbank"u8))
        {
            var s_1 = s.Slice(24);
            if (s_1.Length == 0)
            {
                role = GuardianshipRoles.Bank.RepresentasjonDagligbank;
                return true;
            }
            else
            {
                goto end;
            }
        }

        end:
        role = null;
        return false;
    }

    private static bool TryFindForsikringsselskapRoleByNprValue(
        ReadOnlySpan<char> vergeTjenesteoppgave,
        [NotNullWhen(true)] out ExternalRoleReference? role)
    {
        var s = vergeTjenesteoppgave;
        if (s.StartsWith("forvalteForsikringsavtaler"))
        {
            var s_0 = s.Slice(26);
            if (s_0.Length == 0)
            {
                role = GuardianshipRoles.Forsikringsselskap.ForvalteForsikringsavtaler;
                return true;
            }
            else
            {
                goto end;
            }
        }

        end:
        role = null;
        return false;
    }

    private static bool TryFindForsikringsselskapRoleByNprValue(
        ReadOnlySpan<byte> vergeTjenesteoppgave,
        [NotNullWhen(true)] out ExternalRoleReference? role)
    {
        var s = vergeTjenesteoppgave;
        if (s.StartsWith("forvalteForsikringsavtaler"u8))
        {
            var s_0 = s.Slice(26);
            if (s_0.Length == 0)
            {
                role = GuardianshipRoles.Forsikringsselskap.ForvalteForsikringsavtaler;
                return true;
            }
            else
            {
                goto end;
            }
        }

        end:
        role = null;
        return false;
    }

    private static bool TryFindHelfoRoleByNprValue(
        ReadOnlySpan<char> vergeTjenesteoppgave,
        [NotNullWhen(true)] out ExternalRoleReference? role)
    {
        var s = vergeTjenesteoppgave;
        if (s.StartsWith("fastlege"))
        {
            var s_0 = s.Slice(8);
            if (s_0.Length == 0)
            {
                role = GuardianshipRoles.Helfo.Fastlege;
                return true;
            }
            else
            {
                goto end;
            }
        }

        if (s.StartsWith("refusjonForPrivatpersoner"))
        {
            var s_1 = s.Slice(25);
            if (s_1.Length == 0)
            {
                role = GuardianshipRoles.Helfo.RefusjonForPrivatpersoner;
                return true;
            }
            else
            {
                goto end;
            }
        }

        end:
        role = null;
        return false;
    }

    private static bool TryFindHelfoRoleByNprValue(
        ReadOnlySpan<byte> vergeTjenesteoppgave,
        [NotNullWhen(true)] out ExternalRoleReference? role)
    {
        var s = vergeTjenesteoppgave;
        if (s.StartsWith("fastlege"u8))
        {
            var s_0 = s.Slice(8);
            if (s_0.Length == 0)
            {
                role = GuardianshipRoles.Helfo.Fastlege;
                return true;
            }
            else
            {
                goto end;
            }
        }

        if (s.StartsWith("refusjonForPrivatpersoner"u8))
        {
            var s_1 = s.Slice(25);
            if (s_1.Length == 0)
            {
                role = GuardianshipRoles.Helfo.RefusjonForPrivatpersoner;
                return true;
            }
            else
            {
                goto end;
            }
        }

        end:
        role = null;
        return false;
    }

    private static bool TryFindHusbankenRoleByNprValue(
        ReadOnlySpan<char> vergeTjenesteoppgave,
        [NotNullWhen(true)] out ExternalRoleReference? role)
    {
        var s = vergeTjenesteoppgave;
        if (s.StartsWith("bostoette"))
        {
            var s_0 = s.Slice(9);
            if (s_0.Length == 0)
            {
                role = GuardianshipRoles.Husbanken.Bostøtte;
                return true;
            }
            else
            {
                goto end;
            }
        }

        if (s.StartsWith("startlaan"))
        {
            var s_1 = s.Slice(9);
            if (s_1.Length == 0)
            {
                role = GuardianshipRoles.Husbanken.Startlån;
                return true;
            }
            else
            {
                goto end;
            }
        }

        end:
        role = null;
        return false;
    }

    private static bool TryFindHusbankenRoleByNprValue(
        ReadOnlySpan<byte> vergeTjenesteoppgave,
        [NotNullWhen(true)] out ExternalRoleReference? role)
    {
        var s = vergeTjenesteoppgave;
        if (s.StartsWith("bostoette"u8))
        {
            var s_0 = s.Slice(9);
            if (s_0.Length == 0)
            {
                role = GuardianshipRoles.Husbanken.Bostøtte;
                return true;
            }
            else
            {
                goto end;
            }
        }

        if (s.StartsWith("startlaan"u8))
        {
            var s_1 = s.Slice(9);
            if (s_1.Length == 0)
            {
                role = GuardianshipRoles.Husbanken.Startlån;
                return true;
            }
            else
            {
                goto end;
            }
        }

        end:
        role = null;
        return false;
    }

    private static bool TryFindInkassoselskapRoleByNprValue(
        ReadOnlySpan<char> vergeTjenesteoppgave,
        [NotNullWhen(true)] out ExternalRoleReference? role)
    {
        var s = vergeTjenesteoppgave;
        if (s.StartsWith("forhandleOgInngaaInkassoavtaler"))
        {
            var s_0 = s.Slice(31);
            if (s_0.Length == 0)
            {
                role = GuardianshipRoles.Inkassoselskap.ForhandleOgInngåInkassoavtaler;
                return true;
            }
            else
            {
                goto end;
            }
        }

        end:
        role = null;
        return false;
    }

    private static bool TryFindInkassoselskapRoleByNprValue(
        ReadOnlySpan<byte> vergeTjenesteoppgave,
        [NotNullWhen(true)] out ExternalRoleReference? role)
    {
        var s = vergeTjenesteoppgave;
        if (s.StartsWith("forhandleOgInngaaInkassoavtaler"u8))
        {
            var s_0 = s.Slice(31);
            if (s_0.Length == 0)
            {
                role = GuardianshipRoles.Inkassoselskap.ForhandleOgInngåInkassoavtaler;
                return true;
            }
            else
            {
                goto end;
            }
        }

        end:
        role = null;
        return false;
    }

    private static bool TryFindKartverketRoleByNprValue(
        ReadOnlySpan<char> vergeTjenesteoppgave,
        [NotNullWhen(true)] out ExternalRoleReference? role)
    {
        var s = vergeTjenesteoppgave;
        if (s.StartsWith("s"))
        {
            var s_0 = s.Slice(1);
            if (s_0.StartsWith("letting"))
            {
                var s_0_0 = s_0.Slice(7);
                if (s_0_0.Length == 0)
                {
                    role = GuardianshipRoles.Kartverket.Sletting;
                    return true;
                }
                else
                {
                    goto end;
                }
            }

            if (s_0.StartsWith("algAvFastEiendomBorettslagsandel"))
            {
                var s_0_1 = s_0.Slice(32);
                if (s_0_1.Length == 0)
                {
                    role = GuardianshipRoles.Kartverket.SalgAvFastEiendomBorettslagsandel;
                    return true;
                }
                else
                {
                    goto end;
                }
            }
        }

        if (s.StartsWith("a"))
        {
            var s_1 = s.Slice(1);
            if (s_1.StartsWith("vtalerOgRettigheter"))
            {
                var s_1_0 = s_1.Slice(19);
                if (s_1_0.Length == 0)
                {
                    role = GuardianshipRoles.Kartverket.AvtalerOgRettigheter;
                    return true;
                }
                else
                {
                    goto end;
                }
            }

            if (s_1.StartsWith("rvPrivatSkifteOgUskifte"))
            {
                var s_1_1 = s_1.Slice(23);
                if (s_1_1.Length == 0)
                {
                    role = GuardianshipRoles.Kartverket.ArvPrivatSkifteOgUskifte;
                    return true;
                }
                else
                {
                    goto end;
                }
            }
        }

        if (s.StartsWith("laaneopptak"))
        {
            var s_2 = s.Slice(11);
            if (s_2.Length == 0)
            {
                role = GuardianshipRoles.Kartverket.Låneopptak;
                return true;
            }
            else
            {
                goto end;
            }
        }

        if (s.StartsWith("kjoepAvEiendom"))
        {
            var s_3 = s.Slice(14);
            if (s_3.Length == 0)
            {
                role = GuardianshipRoles.Kartverket.KjøpAvEiendom;
                return true;
            }
            else
            {
                goto end;
            }
        }

        if (s.StartsWith("endringAvEiendom"))
        {
            var s_4 = s.Slice(16);
            if (s_4.Length == 0)
            {
                role = GuardianshipRoles.Kartverket.EndringAvEiendom;
                return true;
            }
            else
            {
                goto end;
            }
        }

        end:
        role = null;
        return false;
    }

    private static bool TryFindKartverketRoleByNprValue(
        ReadOnlySpan<byte> vergeTjenesteoppgave,
        [NotNullWhen(true)] out ExternalRoleReference? role)
    {
        var s = vergeTjenesteoppgave;
        if (s.StartsWith("s"u8))
        {
            var s_0 = s.Slice(1);
            if (s_0.StartsWith("letting"u8))
            {
                var s_0_0 = s_0.Slice(7);
                if (s_0_0.Length == 0)
                {
                    role = GuardianshipRoles.Kartverket.Sletting;
                    return true;
                }
                else
                {
                    goto end;
                }
            }

            if (s_0.StartsWith("algAvFastEiendomBorettslagsandel"u8))
            {
                var s_0_1 = s_0.Slice(32);
                if (s_0_1.Length == 0)
                {
                    role = GuardianshipRoles.Kartverket.SalgAvFastEiendomBorettslagsandel;
                    return true;
                }
                else
                {
                    goto end;
                }
            }
        }

        if (s.StartsWith("a"u8))
        {
            var s_1 = s.Slice(1);
            if (s_1.StartsWith("vtalerOgRettigheter"u8))
            {
                var s_1_0 = s_1.Slice(19);
                if (s_1_0.Length == 0)
                {
                    role = GuardianshipRoles.Kartverket.AvtalerOgRettigheter;
                    return true;
                }
                else
                {
                    goto end;
                }
            }

            if (s_1.StartsWith("rvPrivatSkifteOgUskifte"u8))
            {
                var s_1_1 = s_1.Slice(23);
                if (s_1_1.Length == 0)
                {
                    role = GuardianshipRoles.Kartverket.ArvPrivatSkifteOgUskifte;
                    return true;
                }
                else
                {
                    goto end;
                }
            }
        }

        if (s.StartsWith("laaneopptak"u8))
        {
            var s_2 = s.Slice(11);
            if (s_2.Length == 0)
            {
                role = GuardianshipRoles.Kartverket.Låneopptak;
                return true;
            }
            else
            {
                goto end;
            }
        }

        if (s.StartsWith("kjoepAvEiendom"u8))
        {
            var s_3 = s.Slice(14);
            if (s_3.Length == 0)
            {
                role = GuardianshipRoles.Kartverket.KjøpAvEiendom;
                return true;
            }
            else
            {
                goto end;
            }
        }

        if (s.StartsWith("endringAvEiendom"u8))
        {
            var s_4 = s.Slice(16);
            if (s_4.Length == 0)
            {
                role = GuardianshipRoles.Kartverket.EndringAvEiendom;
                return true;
            }
            else
            {
                goto end;
            }
        }

        end:
        role = null;
        return false;
    }

    private static bool TryFindKommuneRoleByNprValue(
        ReadOnlySpan<char> vergeTjenesteoppgave,
        [NotNullWhen(true)] out ExternalRoleReference? role)
    {
        var s = vergeTjenesteoppgave;
        if (s.StartsWith("s"))
        {
            var s_0 = s.Slice(1);
            if (s_0.StartsWith("k"))
            {
                var s_0_0 = s_0.Slice(1);
                if (s_0_0.StartsWith("attOgAvgift"))
                {
                    var s_0_0_0 = s_0_0.Slice(11);
                    if (s_0_0_0.Length == 0)
                    {
                        role = GuardianshipRoles.Kommune.SkattOgAvgift;
                        return true;
                    }
                    else
                    {
                        goto end;
                    }
                }

                if (s_0_0.StartsWith("oleOgUtdanning"))
                {
                    var s_0_0_1 = s_0_0.Slice(14);
                    if (s_0_0_1.Length == 0)
                    {
                        role = GuardianshipRoles.Kommune.SkoleOgUtdanning;
                        return true;
                    }
                    else
                    {
                        goto end;
                    }
                }
            }

            if (s_0.StartsWith("osialeTjenester"))
            {
                var s_0_1 = s_0.Slice(15);
                if (s_0_1.Length == 0)
                {
                    role = GuardianshipRoles.Kommune.SosialeTjenester;
                    return true;
                }
                else
                {
                    goto end;
                }
            }
        }

        if (s.StartsWith("byggOgEiendom"))
        {
            var s_1 = s.Slice(13);
            if (s_1.Length == 0)
            {
                role = GuardianshipRoles.Kommune.ByggOgEiendom;
                return true;
            }
            else
            {
                goto end;
            }
        }

        if (s.StartsWith("helseOgOmsorg"))
        {
            var s_2 = s.Slice(13);
            if (s_2.Length == 0)
            {
                role = GuardianshipRoles.Kommune.HelseOgOmsorg;
                return true;
            }
            else
            {
                goto end;
            }
        }

        end:
        role = null;
        return false;
    }

    private static bool TryFindKommuneRoleByNprValue(
        ReadOnlySpan<byte> vergeTjenesteoppgave,
        [NotNullWhen(true)] out ExternalRoleReference? role)
    {
        var s = vergeTjenesteoppgave;
        if (s.StartsWith("s"u8))
        {
            var s_0 = s.Slice(1);
            if (s_0.StartsWith("k"u8))
            {
                var s_0_0 = s_0.Slice(1);
                if (s_0_0.StartsWith("attOgAvgift"u8))
                {
                    var s_0_0_0 = s_0_0.Slice(11);
                    if (s_0_0_0.Length == 0)
                    {
                        role = GuardianshipRoles.Kommune.SkattOgAvgift;
                        return true;
                    }
                    else
                    {
                        goto end;
                    }
                }

                if (s_0_0.StartsWith("oleOgUtdanning"u8))
                {
                    var s_0_0_1 = s_0_0.Slice(14);
                    if (s_0_0_1.Length == 0)
                    {
                        role = GuardianshipRoles.Kommune.SkoleOgUtdanning;
                        return true;
                    }
                    else
                    {
                        goto end;
                    }
                }
            }

            if (s_0.StartsWith("osialeTjenester"u8))
            {
                var s_0_1 = s_0.Slice(15);
                if (s_0_1.Length == 0)
                {
                    role = GuardianshipRoles.Kommune.SosialeTjenester;
                    return true;
                }
                else
                {
                    goto end;
                }
            }
        }

        if (s.StartsWith("byggOgEiendom"u8))
        {
            var s_1 = s.Slice(13);
            if (s_1.Length == 0)
            {
                role = GuardianshipRoles.Kommune.ByggOgEiendom;
                return true;
            }
            else
            {
                goto end;
            }
        }

        if (s.StartsWith("helseOgOmsorg"u8))
        {
            var s_2 = s.Slice(13);
            if (s_2.Length == 0)
            {
                role = GuardianshipRoles.Kommune.HelseOgOmsorg;
                return true;
            }
            else
            {
                goto end;
            }
        }

        end:
        role = null;
        return false;
    }

    private static bool TryFindKredittvurderingsselskapRoleByNprValue(
        ReadOnlySpan<char> vergeTjenesteoppgave,
        [NotNullWhen(true)] out ExternalRoleReference? role)
    {
        var s = vergeTjenesteoppgave;
        if (s.StartsWith("kredittsperre"))
        {
            var s_0 = s.Slice(13);
            if (s_0.Length == 0)
            {
                role = GuardianshipRoles.Kredittvurderingsselskap.Kredittsperre;
                return true;
            }
            else
            {
                goto end;
            }
        }

        end:
        role = null;
        return false;
    }

    private static bool TryFindKredittvurderingsselskapRoleByNprValue(
        ReadOnlySpan<byte> vergeTjenesteoppgave,
        [NotNullWhen(true)] out ExternalRoleReference? role)
    {
        var s = vergeTjenesteoppgave;
        if (s.StartsWith("kredittsperre"u8))
        {
            var s_0 = s.Slice(13);
            if (s_0.Length == 0)
            {
                role = GuardianshipRoles.Kredittvurderingsselskap.Kredittsperre;
                return true;
            }
            else
            {
                goto end;
            }
        }

        end:
        role = null;
        return false;
    }

    private static bool TryFindNamsmannenRoleByNprValue(
        ReadOnlySpan<char> vergeTjenesteoppgave,
        [NotNullWhen(true)] out ExternalRoleReference? role)
    {
        var s = vergeTjenesteoppgave;
        if (s.StartsWith("gjeldsordning"))
        {
            var s_0 = s.Slice(13);
            if (s_0.Length == 0)
            {
                role = GuardianshipRoles.Namsmannen.Gjeldsordning;
                return true;
            }
            else
            {
                goto end;
            }
        }

        if (s.StartsWith("tvangsfullbyrdelse"))
        {
            var s_1 = s.Slice(18);
            if (s_1.Length == 0)
            {
                role = GuardianshipRoles.Namsmannen.Tvangsfullbyrdelse;
                return true;
            }
            else
            {
                goto end;
            }
        }

        end:
        role = null;
        return false;
    }

    private static bool TryFindNamsmannenRoleByNprValue(
        ReadOnlySpan<byte> vergeTjenesteoppgave,
        [NotNullWhen(true)] out ExternalRoleReference? role)
    {
        var s = vergeTjenesteoppgave;
        if (s.StartsWith("gjeldsordning"u8))
        {
            var s_0 = s.Slice(13);
            if (s_0.Length == 0)
            {
                role = GuardianshipRoles.Namsmannen.Gjeldsordning;
                return true;
            }
            else
            {
                goto end;
            }
        }

        if (s.StartsWith("tvangsfullbyrdelse"u8))
        {
            var s_1 = s.Slice(18);
            if (s_1.Length == 0)
            {
                role = GuardianshipRoles.Namsmannen.Tvangsfullbyrdelse;
                return true;
            }
            else
            {
                goto end;
            }
        }

        end:
        role = null;
        return false;
    }

    private static bool TryFindNavRoleByNprValue(
        ReadOnlySpan<char> vergeTjenesteoppgave,
        [NotNullWhen(true)] out ExternalRoleReference? role)
    {
        var s = vergeTjenesteoppgave;
        if (s.StartsWith("arbeid"))
        {
            var s_0 = s.Slice(6);
            if (s_0.Length == 0)
            {
                role = GuardianshipRoles.Nav.Arbeid;
                return true;
            }
            else
            {
                goto end;
            }
        }

        if (s.StartsWith("familie"))
        {
            var s_1 = s.Slice(7);
            if (s_1.Length == 0)
            {
                role = GuardianshipRoles.Nav.Familie;
                return true;
            }
            else
            {
                goto end;
            }
        }

        if (s.StartsWith("pensjon"))
        {
            var s_2 = s.Slice(7);
            if (s_2.Length == 0)
            {
                role = GuardianshipRoles.Nav.Pensjon;
                return true;
            }
            else
            {
                goto end;
            }
        }

        if (s.StartsWith("hjelpemidler"))
        {
            var s_3 = s.Slice(12);
            if (s_3.Length == 0)
            {
                role = GuardianshipRoles.Nav.Hjelpemidler;
                return true;
            }
            else
            {
                goto end;
            }
        }

        if (s.StartsWith("sosialeTjenester"))
        {
            var s_4 = s.Slice(16);
            if (s_4.Length == 0)
            {
                role = GuardianshipRoles.Nav.SosialeTjenester;
                return true;
            }
            else
            {
                goto end;
            }
        }

        end:
        role = null;
        return false;
    }

    private static bool TryFindNavRoleByNprValue(
        ReadOnlySpan<byte> vergeTjenesteoppgave,
        [NotNullWhen(true)] out ExternalRoleReference? role)
    {
        var s = vergeTjenesteoppgave;
        if (s.StartsWith("arbeid"u8))
        {
            var s_0 = s.Slice(6);
            if (s_0.Length == 0)
            {
                role = GuardianshipRoles.Nav.Arbeid;
                return true;
            }
            else
            {
                goto end;
            }
        }

        if (s.StartsWith("familie"u8))
        {
            var s_1 = s.Slice(7);
            if (s_1.Length == 0)
            {
                role = GuardianshipRoles.Nav.Familie;
                return true;
            }
            else
            {
                goto end;
            }
        }

        if (s.StartsWith("pensjon"u8))
        {
            var s_2 = s.Slice(7);
            if (s_2.Length == 0)
            {
                role = GuardianshipRoles.Nav.Pensjon;
                return true;
            }
            else
            {
                goto end;
            }
        }

        if (s.StartsWith("hjelpemidler"u8))
        {
            var s_3 = s.Slice(12);
            if (s_3.Length == 0)
            {
                role = GuardianshipRoles.Nav.Hjelpemidler;
                return true;
            }
            else
            {
                goto end;
            }
        }

        if (s.StartsWith("sosialeTjenester"u8))
        {
            var s_4 = s.Slice(16);
            if (s_4.Length == 0)
            {
                role = GuardianshipRoles.Nav.SosialeTjenester;
                return true;
            }
            else
            {
                goto end;
            }
        }

        end:
        role = null;
        return false;
    }

    private static bool TryFindPasientreiserRoleByNprValue(
        ReadOnlySpan<char> vergeTjenesteoppgave,
        [NotNullWhen(true)] out ExternalRoleReference? role)
    {
        var s = vergeTjenesteoppgave;
        if (s.StartsWith("refusjonAvPasientreiser"))
        {
            var s_0 = s.Slice(23);
            if (s_0.Length == 0)
            {
                role = GuardianshipRoles.Pasientreiser.RefusjonAvPasientreiser;
                return true;
            }
            else
            {
                goto end;
            }
        }

        end:
        role = null;
        return false;
    }

    private static bool TryFindPasientreiserRoleByNprValue(
        ReadOnlySpan<byte> vergeTjenesteoppgave,
        [NotNullWhen(true)] out ExternalRoleReference? role)
    {
        var s = vergeTjenesteoppgave;
        if (s.StartsWith("refusjonAvPasientreiser"u8))
        {
            var s_0 = s.Slice(23);
            if (s_0.Length == 0)
            {
                role = GuardianshipRoles.Pasientreiser.RefusjonAvPasientreiser;
                return true;
            }
            else
            {
                goto end;
            }
        }

        end:
        role = null;
        return false;
    }

    private static bool TryFindSkatteetatenRoleByNprValue(
        ReadOnlySpan<char> vergeTjenesteoppgave,
        [NotNullWhen(true)] out ExternalRoleReference? role)
    {
        var s = vergeTjenesteoppgave;
        if (s.StartsWith("skatt"))
        {
            var s_0 = s.Slice(5);
            if (s_0.Length == 0)
            {
                role = GuardianshipRoles.Skatteetaten.Skatt;
                return true;
            }
            else
            {
                goto end;
            }
        }

        if (s.StartsWith("innkreving"))
        {
            var s_1 = s.Slice(10);
            if (s_1.Length == 0)
            {
                role = GuardianshipRoles.Skatteetaten.Innkreving;
                return true;
            }
            else
            {
                goto end;
            }
        }

        if (s.StartsWith("meldeFlytting"))
        {
            var s_2 = s.Slice(13);
            if (s_2.Length == 0)
            {
                role = GuardianshipRoles.Skatteetaten.MeldeFlytting;
                return true;
            }
            else
            {
                goto end;
            }
        }

        if (s.StartsWith("endrePostadresse"))
        {
            var s_3 = s.Slice(16);
            if (s_3.Length == 0)
            {
                role = GuardianshipRoles.Skatteetaten.EndrePostadresse;
                return true;
            }
            else
            {
                goto end;
            }
        }

        end:
        role = null;
        return false;
    }

    private static bool TryFindSkatteetatenRoleByNprValue(
        ReadOnlySpan<byte> vergeTjenesteoppgave,
        [NotNullWhen(true)] out ExternalRoleReference? role)
    {
        var s = vergeTjenesteoppgave;
        if (s.StartsWith("skatt"u8))
        {
            var s_0 = s.Slice(5);
            if (s_0.Length == 0)
            {
                role = GuardianshipRoles.Skatteetaten.Skatt;
                return true;
            }
            else
            {
                goto end;
            }
        }

        if (s.StartsWith("innkreving"u8))
        {
            var s_1 = s.Slice(10);
            if (s_1.Length == 0)
            {
                role = GuardianshipRoles.Skatteetaten.Innkreving;
                return true;
            }
            else
            {
                goto end;
            }
        }

        if (s.StartsWith("meldeFlytting"u8))
        {
            var s_2 = s.Slice(13);
            if (s_2.Length == 0)
            {
                role = GuardianshipRoles.Skatteetaten.MeldeFlytting;
                return true;
            }
            else
            {
                goto end;
            }
        }

        if (s.StartsWith("endrePostadresse"u8))
        {
            var s_3 = s.Slice(16);
            if (s_3.Length == 0)
            {
                role = GuardianshipRoles.Skatteetaten.EndrePostadresse;
                return true;
            }
            else
            {
                goto end;
            }
        }

        end:
        role = null;
        return false;
    }

    private static bool TryFindStatensInnkrevingssentralRoleByNprValue(
        ReadOnlySpan<char> vergeTjenesteoppgave,
        [NotNullWhen(true)] out ExternalRoleReference? role)
    {
        var s = vergeTjenesteoppgave;
        if (s.StartsWith("gjeldsordningOgBetalingsavtaler"))
        {
            var s_0 = s.Slice(31);
            if (s_0.Length == 0)
            {
                role = GuardianshipRoles.StatensInnkrevingssentral.GjeldsordningOgBetalingsavtaler;
                return true;
            }
            else
            {
                goto end;
            }
        }

        end:
        role = null;
        return false;
    }

    private static bool TryFindStatensInnkrevingssentralRoleByNprValue(
        ReadOnlySpan<byte> vergeTjenesteoppgave,
        [NotNullWhen(true)] out ExternalRoleReference? role)
    {
        var s = vergeTjenesteoppgave;
        if (s.StartsWith("gjeldsordningOgBetalingsavtaler"u8))
        {
            var s_0 = s.Slice(31);
            if (s_0.Length == 0)
            {
                role = GuardianshipRoles.StatensInnkrevingssentral.GjeldsordningOgBetalingsavtaler;
                return true;
            }
            else
            {
                goto end;
            }
        }

        end:
        role = null;
        return false;
    }

    private static bool TryFindStatsforvalterRoleByNprValue(
        ReadOnlySpan<char> vergeTjenesteoppgave,
        [NotNullWhen(true)] out ExternalRoleReference? role)
    {
        var s = vergeTjenesteoppgave;
        if (s.StartsWith("soekeOmSamtykkeTilDisposisjon"))
        {
            var s_0 = s.Slice(29);
            if (s_0.Length == 0)
            {
                role = GuardianshipRoles.Statsforvalter.SøkeOmSamtykkeTilDisposisjon;
                return true;
            }
            else
            {
                goto end;
            }
        }

        end:
        role = null;
        return false;
    }

    private static bool TryFindStatsforvalterRoleByNprValue(
        ReadOnlySpan<byte> vergeTjenesteoppgave,
        [NotNullWhen(true)] out ExternalRoleReference? role)
    {
        var s = vergeTjenesteoppgave;
        if (s.StartsWith("soekeOmSamtykkeTilDisposisjon"u8))
        {
            var s_0 = s.Slice(29);
            if (s_0.Length == 0)
            {
                role = GuardianshipRoles.Statsforvalter.SøkeOmSamtykkeTilDisposisjon;
                return true;
            }
            else
            {
                goto end;
            }
        }

        end:
        role = null;
        return false;
    }

    private static bool TryFindTingrettenRoleByNprValue(
        ReadOnlySpan<char> vergeTjenesteoppgave,
        [NotNullWhen(true)] out ExternalRoleReference? role)
    {
        var s = vergeTjenesteoppgave;
        if (s.StartsWith("begjaere"))
        {
            var s_0 = s.Slice(8);
            if (s_0.StartsWith("Uskifte"))
            {
                var s_0_0 = s_0.Slice(7);
                if (s_0_0.Length == 0)
                {
                    role = GuardianshipRoles.Tingretten.BegjæreUskifte;
                    return true;
                }
                else
                {
                    goto end;
                }
            }

            if (s_0.StartsWith("SkifteAvUskiftebo"))
            {
                var s_0_1 = s_0.Slice(17);
                if (s_0_1.Length == 0)
                {
                    role = GuardianshipRoles.Tingretten.BegjæreSkifteAvUskiftebo;
                    return true;
                }
                else
                {
                    goto end;
                }
            }
        }

        if (s.StartsWith("privatSkifteAvDodsbo"))
        {
            var s_1 = s.Slice(20);
            if (s_1.Length == 0)
            {
                role = GuardianshipRoles.Tingretten.PrivatSkifteAvDødsbo;
                return true;
            }
            else
            {
                goto end;
            }
        }

        end:
        role = null;
        return false;
    }

    private static bool TryFindTingrettenRoleByNprValue(
        ReadOnlySpan<byte> vergeTjenesteoppgave,
        [NotNullWhen(true)] out ExternalRoleReference? role)
    {
        var s = vergeTjenesteoppgave;
        if (s.StartsWith("begjaere"u8))
        {
            var s_0 = s.Slice(8);
            if (s_0.StartsWith("Uskifte"u8))
            {
                var s_0_0 = s_0.Slice(7);
                if (s_0_0.Length == 0)
                {
                    role = GuardianshipRoles.Tingretten.BegjæreUskifte;
                    return true;
                }
                else
                {
                    goto end;
                }
            }

            if (s_0.StartsWith("SkifteAvUskiftebo"u8))
            {
                var s_0_1 = s_0.Slice(17);
                if (s_0_1.Length == 0)
                {
                    role = GuardianshipRoles.Tingretten.BegjæreSkifteAvUskiftebo;
                    return true;
                }
                else
                {
                    goto end;
                }
            }
        }

        if (s.StartsWith("privatSkifteAvDodsbo"u8))
        {
            var s_1 = s.Slice(20);
            if (s_1.Length == 0)
            {
                role = GuardianshipRoles.Tingretten.PrivatSkifteAvDødsbo;
                return true;
            }
            else
            {
                goto end;
            }
        }

        end:
        role = null;
        return false;
    }

    private static bool TryFindØvrigeRoleByNprValue(
        ReadOnlySpan<char> vergeTjenesteoppgave,
        [NotNullWhen(true)] out ExternalRoleReference? role)
    {
        var s = vergeTjenesteoppgave;
        if (s.StartsWith("kjoepLeieAvVarerOgTjenester"))
        {
            var s_0 = s.Slice(27);
            if (s_0.Length == 0)
            {
                role = GuardianshipRoles.Øvrige.KjøpLeieAvVarerOgTjenester;
                return true;
            }
            else
            {
                goto end;
            }
        }

        if (s.StartsWith("salgAvLoesoereAvStoerreVerdi"))
        {
            var s_1 = s.Slice(28);
            if (s_1.Length == 0)
            {
                role = GuardianshipRoles.Øvrige.SalgAvLøsøreAvStørreVerdi;
                return true;
            }
            else
            {
                goto end;
            }
        }

        if (s.StartsWith("inngaaelseAvHusleiekontrakter"))
        {
            var s_2 = s.Slice(29);
            if (s_2.Length == 0)
            {
                role = GuardianshipRoles.Øvrige.InngåelseAvHusleiekontrakter;
                return true;
            }
            else
            {
                goto end;
            }
        }

        if (s.StartsWith("avslutningAvHusleiekontrakter"))
        {
            var s_3 = s.Slice(29);
            if (s_3.Length == 0)
            {
                role = GuardianshipRoles.Øvrige.AvslutningAvHusleiekontrakter;
                return true;
            }
            else
            {
                goto end;
            }
        }

        if (s.StartsWith("disponereInntekterTilAaDekkeUtgifter"))
        {
            var s_4 = s.Slice(36);
            if (s_4.Length == 0)
            {
                role = GuardianshipRoles.Øvrige.DisponereInntekterTilÅDekkeUtgifter;
                return true;
            }
            else
            {
                goto end;
            }
        }

        end:
        role = null;
        return false;
    }

    private static bool TryFindØvrigeRoleByNprValue(
        ReadOnlySpan<byte> vergeTjenesteoppgave,
        [NotNullWhen(true)] out ExternalRoleReference? role)
    {
        var s = vergeTjenesteoppgave;
        if (s.StartsWith("kjoepLeieAvVarerOgTjenester"u8))
        {
            var s_0 = s.Slice(27);
            if (s_0.Length == 0)
            {
                role = GuardianshipRoles.Øvrige.KjøpLeieAvVarerOgTjenester;
                return true;
            }
            else
            {
                goto end;
            }
        }

        if (s.StartsWith("salgAvLoesoereAvStoerreVerdi"u8))
        {
            var s_1 = s.Slice(28);
            if (s_1.Length == 0)
            {
                role = GuardianshipRoles.Øvrige.SalgAvLøsøreAvStørreVerdi;
                return true;
            }
            else
            {
                goto end;
            }
        }

        if (s.StartsWith("inngaaelseAvHusleiekontrakter"u8))
        {
            var s_2 = s.Slice(29);
            if (s_2.Length == 0)
            {
                role = GuardianshipRoles.Øvrige.InngåelseAvHusleiekontrakter;
                return true;
            }
            else
            {
                goto end;
            }
        }

        if (s.StartsWith("avslutningAvHusleiekontrakter"u8))
        {
            var s_3 = s.Slice(29);
            if (s_3.Length == 0)
            {
                role = GuardianshipRoles.Øvrige.AvslutningAvHusleiekontrakter;
                return true;
            }
            else
            {
                goto end;
            }
        }

        if (s.StartsWith("disponereInntekterTilAaDekkeUtgifter"u8))
        {
            var s_4 = s.Slice(36);
            if (s_4.Length == 0)
            {
                role = GuardianshipRoles.Øvrige.DisponereInntekterTilÅDekkeUtgifter;
                return true;
            }
            else
            {
                goto end;
            }
        }

        end:
        role = null;
        return false;
    }
}
