-- Generated by `just generate-guardianship-migration`
-- Do not edit manually

INSERT INTO register.external_role_definition ("source", "identifier", "name", "description") VALUES
  (
     'cra',
     'bank-representasjon-dagligbank',
     hstore(ARRAY[
       'nb', 'Bank - Representasjon dagligbank',
       'nn', 'Bank - Representasjon daglegbank',
       'en', 'Bank - Representation daily banking'
     ]),
     hstore(ARRAY[
       'nb', 'Omfatter oppgaver knyttet til å opprette kundeforhold, opprette/avslutte konto, disposisjonsrett, etablere/endre betalingsavtaler og forvalte låneavtaler',
       'nn', 'Omfattar oppgåver knytt til å opprette kundeforhold, opprette/avslutte konto, disposisjonsrett, etablere/endre betalingsavtalar og forvalte låneavtalar',
       'en', 'Includes tasks related to establishing customer relationships, opening/closing accounts, rights of disposition, establishing/changing payment agreements, and managing loan agreements'
     ])
  )
, (
     'cra',
     'bank-ta-opp-lan-kreditter',
     hstore(ARRAY[
       'nb', 'Bank - Ta opp lån/kreditter',
       'nn', 'Bank - Ta opp lån/kredittar',
       'en', 'Bank - Taking out loans/credits'
     ]),
     hstore(ARRAY[
       'nb', 'Gjelder søknad om etablering av banklån - dette krever statsforvalterens samtykke',
       'nn', 'Gjeld søknad om etablering av banklån - dette krev samtykke frå statsforvaltaren',
       'en', 'Applies to applications for establishing bank loans - this requires the consent of the county governor'
     ])
  )
, (
     'cra',
     'forsikringsselskap-forvalte-forsikringsavtaler',
     hstore(ARRAY[
       'nb', 'Forsikringsselskap - Forvalte forsikringsavtaler',
       'nn', 'Forsikringsselskap - Forvalte forsikringsavtalar',
       'en', 'Insurance company - Managing insurance agreements'
     ]),
     hstore(ARRAY[
       'nb', 'Omfatter oppgaver knyttet til å etablere/endre/avslutte forsikringsavtaler og representasjon ved forsikringsoppgjør',
       'nn', 'Omfattar oppgåver knytt til å etablere/endre/avslutte forsikringsavtalar og representasjon ved forsikringsoppgjer',
       'en', 'Includes tasks related to establishing/changing/terminating insurance agreements and representation in insurance settlements'
     ])
  )
, (
     'cra',
     'helfo-refusjon-privatpersoner',
     hstore(ARRAY[
       'nb', 'Helfo - Refusjon for privatpersoner',
       'nn', 'Helfo - Refusjon for privatpersonar',
       'en', 'Helfo - Reimbursement for private individuals'
     ]),
     hstore(ARRAY[
       'nb', 'Gjelder bistand til å søke om stønad til helsetjenester etter folketrygdloven, herunder innsyn i og håndtering av egenandel-/frikortordningen og helsetjenester gitt i utlandet. Gjelder også når en tredjepart sender søknad på vegne av en person (eks. lege, arbeidsgiver, forsikringsselskap)',
       'nn', 'Gjeld bistand til å søke om stønad til helsetenester etter folketrygdlova, herunder innsyn i og handtering av eigenandel-/frikortordninga og helsetenester gitt i utlandet. Gjeld òg når ein tredjepart sender søknad på vegne av ein person (eks. lege, arbeidsgjevar, forsikringsselskap)',
       'en', 'Applies to assistance in applying for benefits for health services under the National Insurance Act, including access to and management of the co-payment/free card scheme and health services provided abroad. Also applies when a third party submits an application on behalf of a person (e.g., doctor, employer, insurance company)'
     ])
  )
, (
     'cra',
     'helfo-fastlege',
     hstore(ARRAY[
       'nb', 'Helfo - Fastlege',
       'nn', 'Helfo - Fastlege',
       'en', 'Helfo - General practitioner'
     ]),
     hstore(ARRAY[
       'nb', 'Gjelder bistand til å bytte fastlege, samt å kunne se tidligere og nåværende fastlege',
       'nn', 'Gjeld bistand til å byte fastlege, samt å kunne sjå tidlegare og noverande fastlege',
       'en', 'Applies to assistance in changing general practitioners, as well as being able to see previous and current general practitioners'
     ])
  )
, (
     'cra',
     'husbanken-bostotte',
     hstore(ARRAY[
       'nb', 'Husbanken - Bostøtte',
       'nn', 'Husbanken - Bustønad',
       'en', 'The Housing Bank - Housing allowance'
     ]),
     hstore(ARRAY[
       'nb', 'Gjelder søknad om og/eller eventuelt klage på vedtak om statlig bostøtte hos Husbanken',
       'nn', 'Gjeld søknad om og/eller eventuelt klage på vedtak om statleg bustønad hos Husbanken',
       'en', 'Applies to applications for and/or possible appeals against decisions on state housing allowance at the Housing Bank'
     ])
  )
, (
     'cra',
     'husbanken-startlan',
     hstore(ARRAY[
       'nb', 'Husbanken - Startlån',
       'nn', 'Husbanken - Startlån',
       'en', 'The Housing Bank - Start-up loan'
     ]),
     hstore(ARRAY[
       'nb', 'Gjelder søknad om og/eller eventuelt klage på vedtak om startlån hos Husbanken',
       'nn', 'Gjeld søknad om og/eller eventuelt klage på vedtak om startlån hos Husbanken',
       'en', 'Applies to applications for and/or possible appeals against decisions on start-up loans at the Housing Bank'
     ])
  )
, (
     'cra',
     'inkassoselskap-inkassoavtaler',
     hstore(ARRAY[
       'nb', 'Inkassoselskap - Forhandle og inngå inkassoavtaler',
       'nn', 'Inkassoselskap - Forhandle og inngå inkassoavtalar',
       'en', 'Debt collection companies - Negotiate and conclude debt collection agreements'
     ]),
     hstore(ARRAY[
       'nb', 'Gjelder avtaleinngåelse og forhandling med ulike inkassoselskaper',
       'nn', 'Gjeld avtaleinngåing og forhandling med ulike inkassoselskap',
       'en', 'Applies to contract conclusion and negotiation with various debt collection companies'
     ])
  )
, (
     'cra',
     'kartverket-salg-fast-eiendom-borettslagsandel',
     hstore(ARRAY[
       'nb', 'Kartverket - Salg av fast eiendom/borettslagsandel',
       'nn', 'Kartverket - Sal av fast eigedom/del av burettslag',
       'en', 'The Norwegian Mapping Authority - Sale of real estate/condominium share'
     ]),
     hstore(ARRAY[
       'nb', 'Omfatter emnene tinglyse eierskifte, sletting av rettighet/servitutt/heftelse, sikringspant. Tjenesteområdet vil også gjelde for overføring av fast eiendom/borettslagsandel mellom ektefeller/samboere - dette krever statsforvalterens samtykke',
       'nn', 'Omfattar emna tinglyse eigarskifte, sletting av rettigheit/servitutt/heftelse, sikringspant. Tenesteområdet vil òg gjelde for overføring av fast eigedom/del av burettslag mellom ektefellar/sambuarar - dette krev samtykke frå statsforvaltaren',
       'en', 'Includes topics such as registering change of ownership, deletion of rights/servitudes/encumbrances, security interests. The service area will also apply to the transfer of real estate/condominium shares between spouses/cohabitants - this requires the consent of the county governor'
     ])
  )
, (
     'cra',
     'kartverket-kjop-eiendom',
     hstore(ARRAY[
       'nb', 'Kartverket - Kjøp av eiendom',
       'nn', 'Kartverket - Kjøp av eigedom',
       'en', 'The Norwegian Mapping Authority - Purchase of property'
     ]),
     hstore(ARRAY[
       'nb', 'Omfatter emnene tinglyse eierskifte, pantsette eiendom, tinglyse avtaler (rettighet/servitutt/heftelse) og festekontrakt - dette krever statsforvalterens samtykke',
       'nn', 'Omfattar emna tinglyse eigarskifte, pantsetje eigedom, tinglyse avtalar (rettigheit/servitutt/heftelse) og festeavtale - dette krev samtykke frå statsforvaltaren',
       'en', 'Includes topics such as registering change of ownership, mortgaging property, registering agreements (rights/servitudes/encumbrances) and lease contracts - this requires the consent of the county governor'
     ])
  )
, (
     'cra',
     'kartverket-arv-privat-skifte-uskifte',
     hstore(ARRAY[
       'nb', 'Kartverket - Arv - privat skifte og uskifte',
       'nn', 'Kartverket - Arv - privat skifte og uskifte',
       'en', 'The Norwegian Mapping Authority - Inheritance - private settlement and undivided estate'
     ]),
     hstore(ARRAY[
       'nb', 'Omfatter emnene hjemmelserklæring og skjøte videre - dette krever statsforvalterens samtykke',
       'nn', 'Omfattar emnene heimelserklæring og skjøte vidare - dette krev samtykke frå statsforvaltaren',
       'en', 'Includes topics such as declaration of title and deed transfer - this requires the consent of the county governor'
     ])
  )
, (
     'cra',
     'kartverket-endring-eiendom',
     hstore(ARRAY[
       'nb', 'Kartverket - Endring av eiendom',
       'nn', 'Kartverket - Endring av eigedom',
       'en', 'The Norwegian Mapping Authority - Change of property'
     ]),
     hstore(ARRAY[
       'nb', 'Omfatter emnene seksjonering, reseksjonering, fradelinger, sammenslåinger, registreringer av festegrunn, endringer av festenummer til bruksnummer, arealoverføring - dette krever statsforvalterens samtykke',
       'nn', 'Omfattar emnene seksjonering, reseksjonering, frådelingar, samanslåingar, registreringar av festegrunn, endringar av festenummer til bruksnummer, arealoverføring - dette krev samtykke frå statsforvaltaren',
       'en', 'Includes topics such as sectioning, resectioning, subdivisions, mergers, registration of leased land, changes from lease number to usage number, area transfer - this requires the consent of the county governor'
     ])
  )
, (
     'cra',
     'kartverket-avtaler-rettigheter',
     hstore(ARRAY[
       'nb', 'Kartverket - Avtaler og rettigheter',
       'nn', 'Kartverket - Avtalar og rettar',
       'en', 'The Norwegian Mapping Authority - Agreements and rights'
     ]),
     hstore(ARRAY[
       'nb', 'Omfatter emnene tinglyse avtaler (rettighet/servitutt/heftelse) og festekontrakt, tinglysning av prioritetsbestemmelser, nedkvitteringer, tinglysing på ny, transport av frivillige heftelser og tvangsforretninger, massetransport - dette krever statsforvalterens samtykke',
       'nn', 'Omfattar emnene tinglyse avtalar (rettigheit/servitutt/heftelse) og festeavtale, tinglysing av prioriteringsbestemmelsar, nedkvitteringar, tinglysing på ny, transport av frivillige heftelser og tvangsforretningar, massetransport - dette krev samtykke frå statsforvaltaren',
       'en', 'Includes topics such as registering agreements (rights/servitudes/encumbrances) and lease contracts, registration of priority provisions, discharges, re-registration, transfer of voluntary encumbrances and enforcement proceedings, mass transport - this requires the consent of the county governor'
     ])
  )
, (
     'cra',
     'kartverket-sletting',
     hstore(ARRAY[
       'nb', 'Kartverket - Sletting',
       'nn', 'Kartverket - Sletting',
       'en', 'The Norwegian Mapping Authority - Deletion'
     ]),
     hstore(ARRAY[
       'nb', 'Gjelder sletting av rettigheter i fast eiendom - dette krever statsforvalterens samtykke',
       'nn', 'Gjeld sletting av rettar i fast eigedom - dette krev samtykke frå statsforvaltaren',
       'en', 'Applies to the deletion of rights in real estate - this requires the consent of the county governor'
     ])
  )
, (
     'cra',
     'kartverket-laneopptak',
     hstore(ARRAY[
       'nb', 'Kartverket - Låneopptak',
       'nn', 'Kartverket - Låneopptak',
       'en', 'The Norwegian Mapping Authority - Loan acquisition'
     ]),
     hstore(ARRAY[
       'nb', 'Omfatter emnene pantsette eiendom, refinansiering - dette krever statsforvalterens samtykke',
       'nn', 'Omfattar emna pantsetje eigedom, refinansiering - dette krev samtykke frå statsforvaltaren',
       'en', 'Includes topics such as mortgaging property, refinancing - this requires the consent of the county governor'
     ])
  )
, (
     'cra',
     'kommune-bygg-eiendom',
     hstore(ARRAY[
       'nb', 'Kommune - Bygg og eiendom',
       'nn', 'Kommune - Bygg og eigedom',
       'en', 'Municipality - Building and property'
     ]),
     hstore(ARRAY[
       'nb', 'Omfatter oppgaver som hører inn under områdene bygging, eiendom, kjøp og salg, leie og utleie, samt priser og gebyr for bygg og eiendom',
       'nn', 'Omfattar oppgåver som høyrer inn under områda bygging, eigedom, kjøp og sal, leige og utleige, samt prisar og gebyr for bygg og eigedom',
       'en', 'Includes tasks that fall under the areas of construction, property, buying and selling, renting and leasing, as well as prices and fees for building and property'
     ])
  )
, (
     'cra',
     'kommune-helse-omsorg',
     hstore(ARRAY[
       'nb', 'Kommune - Helse og omsorg',
       'nn', 'Kommune - Helse og omsorg',
       'en', 'Municipality - Health and care'
     ]),
     hstore(ARRAY[
       'nb', 'Omfatter tilbud og støtteordninger som hører inn under områdene avlastning og støtte, helsetjenester, omsorgstjenester og velferdsstøtte',
       'nn', 'Omfattar tilbod og støtteordningar som høyrer inn under områda avlasting og støtte, helsetenester, omsorgstenester og velferdsstøtte',
       'en', 'Includes services and support schemes that fall under the areas of relief and support, health services, care services, and welfare support'
     ])
  )
, (
     'cra',
     'kommune-skatt-avgift',
     hstore(ARRAY[
       'nb', 'Kommune - Skatt og avgift',
       'nn', 'Kommune - Skatt og avgift',
       'en', 'Municipality - Tax and duty'
     ]),
     hstore(ARRAY[
       'nb', 'Omfatter oppgaver som hører inn under områdene arbeidsgiveravgift, kommunale avgifter, eiendomsskatt og skatteattest',
       'nn', 'Omfattar oppgåver som høyrer inn under områda arbeidsgivaravgift, kommunale avgifter, eigedomsskatt og skatteattest',
       'en', 'Includes tasks that fall under the areas of employer''s national insurance contributions, municipal fees, property tax, and tax certificates'
     ])
  )
, (
     'cra',
     'kommune-sosiale-tjenester',
     hstore(ARRAY[
       'nb', 'Kommune - Sosiale tjenester',
       'nn', 'Kommune - Sosiale tenester',
       'en', 'Municipality - Social services'
     ]),
     hstore(ARRAY[
       'nb', 'Omfatter tilbud og støtteordninger som hører inn under områdene botilbud, kvalifisering til arbeid, økonomiske ytelser og rådgivning',
       'nn', 'Omfattar tilbod og støtteordningar som høyrer inn under områda butilbod, kvalifisering til arbeid, økonomiske ytingar og rådgjeving',
       'en', 'Includes services and support schemes that fall under the areas of housing, qualification for work, financial benefits, and counseling'
     ])
  )
, (
     'cra',
     'kommune-skole-utdanning',
     hstore(ARRAY[
       'nb', 'Kommune - Skole og utdanning',
       'nn', 'Kommune - Skule og utdanning',
       'en', 'Municipality - School and education'
     ]),
     hstore(ARRAY[
       'nb', 'Omfatter tilbud og støtteordninger som hører inn under områdene grunnskole, videregående skole, høyere utdanning, voksenopplæring og skolehverdag',
       'nn', 'Omfattar tilbod og støtteordningar som høyrer inn under områda grunnskule, vidaregåande skule, høgare utdanning, vaksenopplæring og skulekvardag',
       'en', 'Includes services and support schemes that fall under the areas of primary school, secondary school, higher education, adult education, and school everyday life'
     ])
  )
, (
     'cra',
     'kredittvurderingsselskap-kredittsperre',
     hstore(ARRAY[
       'nb', 'Kredittvurderingsselskap - Kredittsperre',
       'nn', 'Kredittvurderingsselskap - Kredittsperre',
       'en', 'Credit rating agency - Credit freeze'
     ]),
     hstore(ARRAY[
       'nb', 'Gjelder avtaleinngåelse om kredittsperre',
       'nn', 'Gjeld avtaleinngåing om kredittsperre',
       'en', 'Applies to contract conclusion regarding credit freeze'
     ])
  )
, (
     'cra',
     'namsmannen-gjeldsordning',
     hstore(ARRAY[
       'nb', 'Namsmannen - Gjeldsordning',
       'nn', 'Namsmannen - Gjeldsordning',
       'en', 'The Enforcement Officer - Debt settlement'
     ]),
     hstore(ARRAY[
       'nb', 'Gjelder søknad om og/eller forvaltning av eksisterende gjeldsordninger',
       'nn', 'Gjeld søknad om og/eller forvaltning av eksisterande gjeldsordningar',
       'en', 'Applies to applications for and/or management of existing debt settlements'
     ])
  )
, (
     'cra',
     'namsmannen-tvangsfullbyrdelse',
     hstore(ARRAY[
       'nb', 'Namsmannen - Tvangsfullbyrdelse',
       'nn', 'Namsmannen - Tvangsfullbyrding',
       'en', 'The Enforcement Officer - Enforcement'
     ]),
     hstore(ARRAY[
       'nb', 'Gjelder representasjon i saker om tvangsfullbyrdelse etter tvangsfullbyrdelsesloven',
       'nn', 'Gjeld representasjon i saker om tvangsfullbyrding etter tvangsfullbyrdingslova',
       'en', 'Applies to representation in cases of enforcement under the Enforcement Act'
     ])
  )
, (
     'cra',
     'nav-arbeid',
     hstore(ARRAY[
       'nb', 'Nav - Arbeid',
       'nn', 'Nav - Arbeid',
       'en', 'Nav - Work'
     ]),
     hstore(ARRAY[
       'nb', 'Omfatter tilbud og støtteordninger som hører inn under områdene forsikring/sykepenger (selvstendig næringsdrivende og frilansere), sykepenger, tilleggsstønad og yrkesskade/menerstatning og arbeidsavklaringspenger. Gjelder innsyn/saksbehandling og utbetaling',
       'nn', 'Omfattar tilbod og støtteordningar som høyrer inn under områda forsikring/sjukepengar (sjålvstendig næringsdrivande og frilansarar), sjukepengar, tilleggstønad og yrkesskade/menerstatning og arbeidsavklaringspengar. Gjeld innsyn/saksbehandling og utbetaling',
       'en', 'Includes services and support schemes that fall under the areas of insurance/sick pay (self-employed and freelancers), sick pay, additional benefits, occupational injury/compensation, and work assessment allowance. Applies to access/case processing and payment'
     ])
  )
, (
     'cra',
     'nav-familie',
     hstore(ARRAY[
       'nb', 'Nav - Familie',
       'nn', 'Nav - Familie',
       'en', 'Nav - Family'
     ]),
     hstore(ARRAY[
       'nb', 'Omfatter tilbud og støtteordninger som hører inn under områdene barnebidrag, barnetrygd, enslig forsørger, foreldre- og svangerskapspenger, grunn- og hjelpestønad og kontantstøtte. Gjelder innsyn/saksbehandling og utbetaling',
       'nn', 'Omfattar tilbod og støtteordningar som høyrer inn under områda barnebidrag, barnetrygd, einsleg forsørgjar, foreldre- og svangerskapspengar, grunn- og hjelpestønad og kontantstøtte. Gjeld innsyn/saksbehandling og utbetaling',
       'en', 'Includes services and support schemes that fall under the areas of child support, child benefit, single provider, parental and pregnancy benefits, basic and assistance benefits, and cash benefits. Applies to access/case processing and payment'
     ])
  )
, (
     'cra',
     'nav-hjelpemidler',
     hstore(ARRAY[
       'nb', 'Nav - Hjelpemidler',
       'nn', 'Nav - Hjelpemiddel',
       'en', 'Nav - Assistive devices'
     ]),
     hstore(ARRAY[
       'nb', 'Omfatter emnene hjelpemidler, helsetjenester, ortopediske hjelpemidler og bil',
       'nn', 'Omfattar emna hjelpemiddel, helsetenester, ortopediske hjelpemiddel og bil',
       'en', 'Includes the topics of assistive devices, health services, orthopedic aids, and cars'
     ])
  )
, (
     'cra',
     'nav-pensjon',
     hstore(ARRAY[
       'nb', 'Nav - Pensjon',
       'nn', 'Nav - Pensjon',
       'en', 'Nav - Pension'
     ]),
     hstore(ARRAY[
       'nb', 'Omfatter tilbud og støtteordninger som hører inn under områdene alderspensjon, supplerende stønad, uførepensjon/-trygd, avtalefestet pensjon, ytelser for gjenlevende (alle typer pensjonsytelser). Gjelder innsyn/saksbehandling og utbetaling',
       'nn', 'Omfattar tilbod og støtteordningar som høyrer inn under områda alderspensjon, supplerande stønad, uførepensjon/-trygd, avtalefesta pensjon, ytingar for gjenlevande (alle typar pensjonsytingar). Gjeld innsyn/saksbehandling og utbetaling',
       'en', 'Includes services and support schemes that fall under the areas of old-age pension, supplementary benefits, disability pension/benefits, contractual pension, benefits for survivors (all types of pension benefits). Applies to access/case processing and payment'
     ])
  )
, (
     'cra',
     'nav-sosiale-tjenester',
     hstore(ARRAY[
       'nb', 'Nav - Sosiale tjenester',
       'nn', 'Nav - Sosiale tenester',
       'en', 'Nav - Social services'
     ]),
     hstore(ARRAY[
       'nb', 'Omfatter tilbud og støtteordninger som hører inn under områdene gjeldsrådgivning, kvalifiseringsprogrammet, midlertidig botilbud, økonomisk rådgivning, forsvarlig livsopphold, midlertidig inntektssikring og økonomisk stønad. Gjelder innsyn/saksbehandling og utbetaling',
       'nn', 'Omfattar tilbod og støtteordningar som høyrer inn under områda gjeldsrådgjeving, kvalifiseringsprogrammet, midlertidig butilbod, økonomisk rådgjeving, forsvarleg livsopphald, midlertidig inntektssikring og økonomisk stønad. Gjeld innsyn/saksbehandling og utbetaling',
       'en', 'Includes services and support schemes that fall under the areas of debt counseling, qualification program, temporary housing, financial counseling, adequate livelihood, temporary income security, and financial assistance. Applies to access/case processing and payment'
     ])
  )
, (
     'cra',
     'pasientreiser-refusjon-pasientreiser',
     hstore(ARRAY[
       'nb', 'Pasientreiser - Refusjon av pasientreiser',
       'nn', 'Pasientreiser - Refusjon av pasientreiser',
       'en', 'Patient travel - Reimbursement of patient travel'
     ]),
     hstore(ARRAY[
       'nb', 'Søknad om og/eller eventuell klage på vedtak om refusjon av reiseutgifter i forbindelse med behandlinger som dekkes av det offentlige',
       'nn', 'Søknad om og/eller eventuell klage på vedtak om refusjon av reiseutgifter i samband med behandlingar som vert dekka av det offentlege',
       'en', 'Application for and/or possible appeal against decisions on reimbursement of travel expenses in connection with treatments covered by the public sector'
     ])
  )
, (
     'cra',
     'skatteetaten-innkreving',
     hstore(ARRAY[
       'nb', 'Skatteetaten - Innkreving',
       'nn', 'Skatteetaten - Innkrevjing',
       'en', 'The Tax Administration - Collection'
     ]),
     hstore(ARRAY[
       'nb', 'Gjelder oppfølging og behandling av krav fra Skatteetaten, for eksempel restskatt',
       'nn', 'Gjeld oppfølging og behandling av krav frå Skatteetaten, for eksempel restskatt',
       'en', 'Applies to follow-up and processing of claims from the Tax Administration, for example, residual tax'
     ])
  )
, (
     'cra',
     'skatteetaten-endre-postadresse',
     hstore(ARRAY[
       'nb', 'Skatteetaten - Endre postadresse',
       'nn', 'Skatteetaten - Endre postadresse',
       'en', 'The Tax Administration - Change postal address'
     ]),
     hstore(ARRAY[
       'nb', 'Gjelder endring av postadresse for person med verge',
       'nn', 'Gjeld endring av postadresse for person med verge',
       'en', 'Applies to changing the postal address for a person with a guardian'
     ])
  )
, (
     'cra',
     'skatteetaten-melde-flytting',
     hstore(ARRAY[
       'nb', 'Skatteetaten - Melde flytting',
       'nn', 'Skatteetaten - Melde flytting',
       'en', 'The Tax Administration - Report moving'
     ]),
     hstore(ARRAY[
       'nb', 'Gjelder endring av bostedsadresse',
       'nn', 'Gjeld endring av bustadsadresse',
       'en', 'Applies to changing the residential address'
     ])
  )
, (
     'cra',
     'skatteetaten-skatt',
     hstore(ARRAY[
       'nb', 'Skatteetaten - Skatt',
       'nn', 'Skatteetaten - Skatt',
       'en', 'The Tax Administration - Tax'
     ]),
     hstore(ARRAY[
       'nb', 'Gjelder innsyn i skattedata, og representasjon overfor skattemyndighetene i alle saker om skatteforhold, herunder endring av skattekort, levering av skattemelding, skatteoppgjør og det ordinære løpet for restskatt eller penger til gode.',
       'nn', 'Gjeld innsyn i skattedata, og representasjon overfor skattemyndigheitene i alle saker om skatteforhold, herunder endring av skattekort, levering av skattemelding, skatteoppgjer og det ordinære løpet for restskatt eller pengar til gode.',
       'en', 'Applies to access to tax data and representation before the tax authorities in all matters concerning tax issues, including changing tax cards, submitting tax returns, tax settlements, and the ordinary course of residual tax or money owed.'
     ])
  )
, (
     'cra',
     'statens-innkrevingssentral-gjeldsordning-betalingsavtaler',
     hstore(ARRAY[
       'nb', 'Statens innkrevingssentral - Gjeldsordning og betalingsavtaler',
       'nn', 'Statens innkrevingssentral - Gjeldsordning og betalingsavtalar',
       'en', 'The Norwegian National Collection Agency - Debt settlement and payment agreements'
     ]),
     hstore(ARRAY[
       'nb', 'Gjelder søknad om og forvaltning av gjeldsordning og betalingsavtaler',
       'nn', 'Gjeld søknad om og forvaltning av gjeldsordning og betalingsavtalar',
       'en', 'Applies to applications for and management of debt settlements and payment agreements'
     ])
  )
, (
     'cra',
     'statsforvalter-soke-om-samtykke-disposisjon',
     hstore(ARRAY[
       'nb', 'Statsforvalter - Søke om samtykke til disposisjon',
       'nn', 'Statsforvalter - Søkje om samtykke til disposisjon',
       'en', 'County Governor - Apply for consent to disposition'
     ]),
     hstore(ARRAY[
       'nb', 'Gjelder søknad om disposisjoner som krever statsforvalterens samtykke',
       'nn', 'Gjeld søknad om disposisjonar som krev samtykke frå statsforvaltaren',
       'en', 'Applies to applications for dispositions that require the consent of the county governor'
     ])
  )
, (
     'cra',
     'tingretten-begjaere-uskifte',
     hstore(ARRAY[
       'nb', 'Tingretten - Begjære uskifte',
       'nn', 'Tingretten - Begjære uskifte',
       'en', 'The District Court - Petition for undivided estate'
     ]),
     hstore(ARRAY[
       'nb', 'Gjelder melding om uskiftet bo jf. vgml. § 41 (3) og arvl. §§ 14 og 32 - dette krever statsforvalterens samtykke',
       'nn', 'Gjeld melding om uskifta bu jf. vgml. § 41 (3) og arvl. §§ 14 og 32 - dette krev samtykke frå statsforvaltaren',
       'en', 'Applies to notification of undivided estate pursuant to the vgml. § 41 (3) and arvl. §§ 14 and 32 - this requires the consent of the county governor'
     ])
  )
, (
     'cra',
     'tingretten-privat-skifte-dodsbo',
     hstore(ARRAY[
       'nb', 'Tingretten - Privat skifte av dødsbo',
       'nn', 'Tingretten - Privat skifte av dødsbu',
       'en', 'The District Court - Private settlement of estate'
     ]),
     hstore(ARRAY[
       'nb', 'Omfatter tilfeller der vergen på vegne av vergehaveren overtar boet til privat skifte og ivaretakelse av andre rettigheter som arving',
       'nn', 'Omfattar tilfelle der vergen på vegne av vergehavaren overtek buet til privat skifte og ivaretaking av andre rettar som arvigar',
       'en', 'Includes cases where the guardian, on behalf of the ward, takes over the estate for private settlement and safeguarding of other rights as an heir'
     ])
  )
, (
     'cra',
     'tingretten-begjaere-skifte-uskiftebo',
     hstore(ARRAY[
       'nb', 'Tingretten - Begjære skifte av uskiftebo',
       'nn', 'Tingretten - Begjære skifte av uskiftebu',
       'en', 'The District Court - Petition for settlement of undivided estate'
     ]),
     hstore(ARRAY[
       'nb', 'Gjelder skifte av uskiftebo jf. vgml. § 41 (3) og arvl. §§ 28 og 29 - dette krever statsforvalterens samtykke',
       'nn', 'Gjeld skifte av uskiftebu jf. vgml. § 41 (3) og arvl. §§ 28 og 29 - dette krev samtykke frå statsforvaltaren',
       'en', 'Applies to settlement of undivided estate pursuant to the vgml. § 41 (3) and arvl. §§ 28 and 29 - this requires the consent of the county governor'
     ])
  )
, (
     'cra',
     'ovrige-kjop-leie-varer-tjenester',
     hstore(ARRAY[
       'nb', 'Øvrige - Kjøp/leie av varer og tjenester',
       'nn', 'Øvrige - Kjøp/leige av varer og tenester',
       'en', 'Others - Purchase/rental of goods and services'
     ]),
     hstore(ARRAY[
       'nb', 'Gjelder i forbindelse med kjøp av varer og tjenester, omfatter også heving av avtaler, reklamasjon mm.',
       'nn', 'Gjelder i samband med kjøp av varer og tenester, omfattar òg heving av avtalar, reklamasjon mm.',
       'en', 'Applies in connection with the purchase of goods and services, also includes termination of agreements, complaints, etc.'
     ])
  )
, (
     'cra',
     'ovrige-inngaelse-husleiekontrakter',
     hstore(ARRAY[
       'nb', 'Øvrige - Inngåelse av husleiekontrakter',
       'nn', 'Øvrige - Inngåing av husleigekontraktar',
       'en', 'Others - Conclusion of lease agreements'
     ]),
     hstore(ARRAY[
       'nb', 'Gjelder i forbindelse med inngåelse av husleiekontrakter',
       'nn', 'Gjelder i samband med inngåing av husleigekontraktar',
       'en', 'Applies in connection with the conclusion of lease agreements'
     ])
  )
, (
     'cra',
     'ovrige-avslutning-husleiekontrakter',
     hstore(ARRAY[
       'nb', 'Øvrige - Avslutning av husleiekontrakter',
       'nn', 'Øvrige - Avslutting av husleigekontraktar',
       'en', 'Others - Termination of lease agreements'
     ]),
     hstore(ARRAY[
       'nb', 'Gjelder i forbindelse med avslutning av husleiekontrakter',
       'nn', 'Gjeld i samband med avslutting av husleigekontraktar',
       'en', 'Applies in connection with the termination of lease agreements'
     ])
  )
, (
     'cra',
     'ovrige-salg-losore-storre-verdi',
     hstore(ARRAY[
       'nb', 'Øvrige - Salg av løsøre av større verdi',
       'nn', 'Øvrige - Sal av lausøyre av større verdi',
       'en', 'Others - Sale of personal property of greater value'
     ]),
     hstore(ARRAY[
       'nb', 'Gjelder salg av løsøre av større verdi (herunder bil), usedvanlig karakter eller av spesiell interesse for vergehaver eller dennes nærmeste familie - dette krever statsforvalterens samtykke',
       'nn', 'Gjeld sal av lausøyre av større verdi (herunder bil), usedvanleg karakter eller av spesiell interesse for vergehavar eller dennes næraste familie - dette krev samtykke frå statsforvaltaren',
       'en', 'Applies to the sale of personal property of greater value (including cars), unusual character, or of special interest to the ward or their immediate family - this requires the consent of the county governor'
     ])
  )
, (
     'cra',
     'ovrige-disponere-inntekter-dekke-utgifter',
     hstore(ARRAY[
       'nb', 'Øvrige - Disponere inntekter til å dekke utgifter',
       'nn', 'Øvrige - Disponere inntekter til å dekkje utgifter',
       'en', 'Others - Dispose of income to cover expenses'
     ]),
     hstore(ARRAY[
       'nb', 'Gjelder adgangen til å bruke vergehaverens inntekter til å betale regninger, betjene gjeld, og dekke øvrige utgifter',
       'nn', 'Gjeld løyve til å bruke vergehavaren sine inntekter til å betale rekningar, betene gjeld, og dekke øvrige utgifter',
       'en', 'Applies to the right to use the ward''s income to pay bills, service debt, and cover other expenses'
     ])
  )
ON CONFLICT (source, identifier) DO UPDATE
    SET "name" = EXCLUDED."name",
        "description" = EXCLUDED."description";
