// This file is autogenerated. Do not edit directly.
#nullable enable

using Altinn.Register.Contracts;
using Altinn.Register.Contracts.ExternalRoles;
using Altinn.Register.PartyImport.Npr;
using System.Diagnostics.CodeAnalysis;

namespace Altinn.Register.Tests.PartyImport.Npr;

/// <summary>Tests for mapping of guardianship roles.</summary>
public static partial class GuardianshipRoleMapperTests
{
    private static partial TheoryData<GuardianshipMetadata> GetGuardianshipRoles()
    {
        return new([
            new GuardianshipMetadata
            {
                Identifier = "bank-representasjon-dagligbank",
                Role = GuardianshipRoles.Bank.RepresentasjonDagligbank,
                NprArea = "bank",
                NprTask = "representasjonDagligbank",
            },
            new GuardianshipMetadata
            {
                Identifier = "bank-ta-opp-lan-kreditter",
                Role = GuardianshipRoles.Bank.TaOppLånKreditter,
                NprArea = "bank",
                NprTask = "taOppLaanKreditter",
            },
            new GuardianshipMetadata
            {
                Identifier = "forsikringsselskap-forvalte-forsikringsavtaler",
                Role = GuardianshipRoles.Forsikringsselskap.ForvalteForsikringsavtaler,
                NprArea = "forsikringsselskap",
                NprTask = "forvalteForsikringsavtaler",
            },
            new GuardianshipMetadata
            {
                Identifier = "helfo-refusjon-privatpersoner",
                Role = GuardianshipRoles.Helfo.RefusjonForPrivatpersoner,
                NprArea = "helfo",
                NprTask = "refusjonForPrivatpersoner",
            },
            new GuardianshipMetadata
            {
                Identifier = "helfo-fastlege",
                Role = GuardianshipRoles.Helfo.Fastlege,
                NprArea = "helfo",
                NprTask = "fastlege",
            },
            new GuardianshipMetadata
            {
                Identifier = "husbanken-bostotte",
                Role = GuardianshipRoles.Husbanken.Bostøtte,
                NprArea = "husbanken",
                NprTask = "bostoette",
            },
            new GuardianshipMetadata
            {
                Identifier = "husbanken-startlan",
                Role = GuardianshipRoles.Husbanken.Startlån,
                NprArea = "husbanken",
                NprTask = "startlaan",
            },
            new GuardianshipMetadata
            {
                Identifier = "inkassoselskap-inkassoavtaler",
                Role = GuardianshipRoles.Inkassoselskap.ForhandleOgInngåInkassoavtaler,
                NprArea = "inkassoselskap",
                NprTask = "forhandleOgInngaaInkassoavtaler",
            },
            new GuardianshipMetadata
            {
                Identifier = "kartverket-salg-fast-eiendom-borettslagsandel",
                Role = GuardianshipRoles.Kartverket.SalgAvFastEiendomBorettslagsandel,
                NprArea = "kartverket",
                NprTask = "salgAvFastEiendomBorettslagsandel",
            },
            new GuardianshipMetadata
            {
                Identifier = "kartverket-kjop-eiendom",
                Role = GuardianshipRoles.Kartverket.KjøpAvEiendom,
                NprArea = "kartverket",
                NprTask = "kjoepAvEiendom",
            },
            new GuardianshipMetadata
            {
                Identifier = "kartverket-arv-privat-skifte-uskifte",
                Role = GuardianshipRoles.Kartverket.ArvPrivatSkifteOgUskifte,
                NprArea = "kartverket",
                NprTask = "arvPrivatSkifteOgUskifte",
            },
            new GuardianshipMetadata
            {
                Identifier = "kartverket-endring-eiendom",
                Role = GuardianshipRoles.Kartverket.EndringAvEiendom,
                NprArea = "kartverket",
                NprTask = "endringAvEiendom",
            },
            new GuardianshipMetadata
            {
                Identifier = "kartverket-avtaler-rettigheter",
                Role = GuardianshipRoles.Kartverket.AvtalerOgRettigheter,
                NprArea = "kartverket",
                NprTask = "avtalerOgRettigheter",
            },
            new GuardianshipMetadata
            {
                Identifier = "kartverket-sletting",
                Role = GuardianshipRoles.Kartverket.Sletting,
                NprArea = "kartverket",
                NprTask = "sletting",
            },
            new GuardianshipMetadata
            {
                Identifier = "kartverket-laneopptak",
                Role = GuardianshipRoles.Kartverket.Låneopptak,
                NprArea = "kartverket",
                NprTask = "laaneopptak",
            },
            new GuardianshipMetadata
            {
                Identifier = "kommune-bygg-eiendom",
                Role = GuardianshipRoles.Kommune.ByggOgEiendom,
                NprArea = "kommune",
                NprTask = "byggOgEiendom",
            },
            new GuardianshipMetadata
            {
                Identifier = "kommune-helse-omsorg",
                Role = GuardianshipRoles.Kommune.HelseOgOmsorg,
                NprArea = "kommune",
                NprTask = "helseOgOmsorg",
            },
            new GuardianshipMetadata
            {
                Identifier = "kommune-skatt-avgift",
                Role = GuardianshipRoles.Kommune.SkattOgAvgift,
                NprArea = "kommune",
                NprTask = "skattOgAvgift",
            },
            new GuardianshipMetadata
            {
                Identifier = "kommune-sosiale-tjenester",
                Role = GuardianshipRoles.Kommune.SosialeTjenester,
                NprArea = "kommune",
                NprTask = "sosialeTjenester",
            },
            new GuardianshipMetadata
            {
                Identifier = "kommune-skole-utdanning",
                Role = GuardianshipRoles.Kommune.SkoleOgUtdanning,
                NprArea = "kommune",
                NprTask = "skoleOgUtdanning",
            },
            new GuardianshipMetadata
            {
                Identifier = "kredittvurderingsselskap-kredittsperre",
                Role = GuardianshipRoles.Kredittvurderingsselskap.Kredittsperre,
                NprArea = "kredittvurderingsselskap",
                NprTask = "kredittsperre",
            },
            new GuardianshipMetadata
            {
                Identifier = "namsmannen-gjeldsordning",
                Role = GuardianshipRoles.Namsmannen.Gjeldsordning,
                NprArea = "namsmannen",
                NprTask = "gjeldsordning",
            },
            new GuardianshipMetadata
            {
                Identifier = "namsmannen-tvangsfullbyrdelse",
                Role = GuardianshipRoles.Namsmannen.Tvangsfullbyrdelse,
                NprArea = "namsmannen",
                NprTask = "tvangsfullbyrdelse",
            },
            new GuardianshipMetadata
            {
                Identifier = "nav-arbeid",
                Role = GuardianshipRoles.Nav.Arbeid,
                NprArea = "nav",
                NprTask = "arbeid",
            },
            new GuardianshipMetadata
            {
                Identifier = "nav-familie",
                Role = GuardianshipRoles.Nav.Familie,
                NprArea = "nav",
                NprTask = "familie",
            },
            new GuardianshipMetadata
            {
                Identifier = "nav-hjelpemidler",
                Role = GuardianshipRoles.Nav.Hjelpemidler,
                NprArea = "nav",
                NprTask = "hjelpemidler",
            },
            new GuardianshipMetadata
            {
                Identifier = "nav-pensjon",
                Role = GuardianshipRoles.Nav.Pensjon,
                NprArea = "nav",
                NprTask = "pensjon",
            },
            new GuardianshipMetadata
            {
                Identifier = "nav-sosiale-tjenester",
                Role = GuardianshipRoles.Nav.SosialeTjenester,
                NprArea = "nav",
                NprTask = "sosialeTjenester",
            },
            new GuardianshipMetadata
            {
                Identifier = "pasientreiser-refusjon-pasientreiser",
                Role = GuardianshipRoles.Pasientreiser.RefusjonAvPasientreiser,
                NprArea = "pasientreiser",
                NprTask = "refusjonAvPasientreiser",
            },
            new GuardianshipMetadata
            {
                Identifier = "skatteetaten-innkreving",
                Role = GuardianshipRoles.Skatteetaten.Innkreving,
                NprArea = "skatteetaten",
                NprTask = "innkreving",
            },
            new GuardianshipMetadata
            {
                Identifier = "skatteetaten-endre-postadresse",
                Role = GuardianshipRoles.Skatteetaten.EndrePostadresse,
                NprArea = "skatteetaten",
                NprTask = "endrePostadresse",
            },
            new GuardianshipMetadata
            {
                Identifier = "skatteetaten-melde-flytting",
                Role = GuardianshipRoles.Skatteetaten.MeldeFlytting,
                NprArea = "skatteetaten",
                NprTask = "meldeFlytting",
            },
            new GuardianshipMetadata
            {
                Identifier = "skatteetaten-skatt",
                Role = GuardianshipRoles.Skatteetaten.Skatt,
                NprArea = "skatteetaten",
                NprTask = "skatt",
            },
            new GuardianshipMetadata
            {
                Identifier = "statens-innkrevingssentral-gjeldsordning-betalingsavtaler",
                Role = GuardianshipRoles.StatensInnkrevingssentral.GjeldsordningOgBetalingsavtaler,
                NprArea = "statensInnkrevingssentral",
                NprTask = "gjeldsordningOgBetalingsavtaler",
            },
            new GuardianshipMetadata
            {
                Identifier = "statsforvalter-soke-om-samtykke-disposisjon",
                Role = GuardianshipRoles.Statsforvalter.SøkeOmSamtykkeTilDisposisjon,
                NprArea = "statsforvalter",
                NprTask = "soekeOmSamtykkeTilDisposisjon",
            },
            new GuardianshipMetadata
            {
                Identifier = "tingretten-begjaere-uskifte",
                Role = GuardianshipRoles.Tingretten.BegjæreUskifte,
                NprArea = "tingretten",
                NprTask = "begjaereUskifte",
            },
            new GuardianshipMetadata
            {
                Identifier = "tingretten-privat-skifte-dodsbo",
                Role = GuardianshipRoles.Tingretten.PrivatSkifteAvDødsbo,
                NprArea = "tingretten",
                NprTask = "privatSkifteAvDodsbo",
            },
            new GuardianshipMetadata
            {
                Identifier = "tingretten-begjaere-skifte-uskiftebo",
                Role = GuardianshipRoles.Tingretten.BegjæreSkifteAvUskiftebo,
                NprArea = "tingretten",
                NprTask = "begjaereSkifteAvUskiftebo",
            },
            new GuardianshipMetadata
            {
                Identifier = "ovrige-kjop-leie-varer-tjenester",
                Role = GuardianshipRoles.Øvrige.KjøpLeieAvVarerOgTjenester,
                NprArea = "oevrige",
                NprTask = "kjoepLeieAvVarerOgTjenester",
            },
            new GuardianshipMetadata
            {
                Identifier = "ovrige-inngaelse-husleiekontrakter",
                Role = GuardianshipRoles.Øvrige.InngåelseAvHusleiekontrakter,
                NprArea = "oevrige",
                NprTask = "inngaaelseAvHusleiekontrakter",
            },
            new GuardianshipMetadata
            {
                Identifier = "ovrige-avslutning-husleiekontrakter",
                Role = GuardianshipRoles.Øvrige.AvslutningAvHusleiekontrakter,
                NprArea = "oevrige",
                NprTask = "avslutningAvHusleiekontrakter",
            },
            new GuardianshipMetadata
            {
                Identifier = "ovrige-salg-losore-storre-verdi",
                Role = GuardianshipRoles.Øvrige.SalgAvLøsøreAvStørreVerdi,
                NprArea = "oevrige",
                NprTask = "salgAvLoesoereAvStoerreVerdi",
            },
            new GuardianshipMetadata
            {
                Identifier = "ovrige-disponere-inntekter-dekke-utgifter",
                Role = GuardianshipRoles.Øvrige.DisponereInntekterTilÅDekkeUtgifter,
                NprArea = "oevrige",
                NprTask = "disponereInntekterTilAaDekkeUtgifter",
            },
        ]);
    }
}
