-- Data: register.country
INSERT INTO register.country (code2, code3, "name")
VALUES
  ('NO', 'NOR', 'NORGE'),
  ('DK', 'DNK', 'DANMARK'),
  ('GL', 'GRL', 'GRØNLAND'),
  ('FI', 'FIN', 'FINLAND'),
  ('FO', 'FRO', 'FÆRØYENE'),
  ('IS', 'ISL', 'ISLAND'),
  ('SE', 'SWE', 'SVERIGE'),
  ('AL', 'ALB', 'ALBANIA'),
  ('BE', 'BEL', 'BELGIA'),
  ('BG', 'BGR', 'BULGARIA'),
  ('AD', 'AND', 'ANDORRA'),
  ('EE', 'EST', 'ESTLAND'),
  ('FR', 'FRA', 'FRANKRIKE'),
  ('GI', 'GIB', 'GIBRALTAR'),
  ('GR', 'GRC', 'HELLAS'),
  ('BY', 'BLR', 'HVITERUSSLAND'),
  ('IE', 'IRL', 'IRLAND'),
  ('HR', 'HRV', 'KROATIA'),
  ('IT', 'ITA', 'ITALIA'),
  ('LV', 'LVA', 'LATVIA'),
  ('MT', 'MLT', 'MALTA'),
  ('NL', 'NLD', 'NEDERLAND'),
  ('LI', 'LIE', 'LIECHTENSTEIN'),
  ('LU', 'LUX', 'LUXEMBOURG'),
  ('MC', 'MCO', 'MONACO'),
  ('PL', 'POL', 'POLEN'),
  ('PT', 'PRT', 'PORTUGAL'),
  ('RO', 'ROU', 'ROMANIA'),
  ('SM', 'SMR', 'SAN MARINO'),
  ('LT', 'LTU', 'LITAUEN'),
  ('ES', 'ESP', 'SPANIA'),
  ('MD', 'MDA', 'MOLDOVA'),
  ('GB', 'GBR', 'STORBRITANNIA'),
  ('RU', 'RUS', 'RUSSLAND'),
  ('CH', 'CHE', 'SVEITS'),
  ('TR', 'TUR', 'TYRKIA'),
  ('DE', 'DEU', 'TYSKLAND'),
  ('SI', 'SVN', 'SLOVENIA'),
  ('UA', 'UKR', 'UKRAINA'),
  ('HU', 'HUN', 'UNGARN'),
  ('AT', 'AUT', 'ØSTERRIKE'),
  ('VA', 'VAT', 'VATIKANSTATEN'),
  ('BA', 'BIH', 'BOSNIA-HERCEGOVINA'),
  ('MK', 'MKD', 'MAKEDONIA'),
  ('SK', 'SVK', 'SLOVAKIA'),
  ('CZ', 'CZE', 'DEN TSJEKKISKE REP.'),
  ('RS', 'SRB', 'SERBIA'),
  ('ME', 'MNE', 'MONTENEGRO'),
  ('XK', 'XXK', 'KOSOVO'),
  ('GG', 'GGY', 'GUERNSEY'),
  ('JE', 'JEY', 'JERSEY'),
  ('IM', 'IMN', 'MAN'),
  ('DZ', 'DZA', 'ALGERIE'),
  ('AO', 'AGO', 'ANGOLA'),
  ('BW', 'BWA', 'BOTSWANA'),
  ('SH', 'SHN', 'ST.HELENA'),
  ('IO', 'IOT', 'BRITISK-INDISKE HAV'),
  ('BI', 'BDI', 'BURUNDI'),
  ('KM', 'COM', 'KOMORENE'),
  ('BJ', 'BEN', 'BENIN'),
  ('GQ', 'GNQ', 'EKVATORIAL-GUINEA'),
  ('CI', 'CIV', 'ELFENBEINSKYSTEN'),
  ('ER', 'ERI', 'ERITREA'),
  ('ET', 'ETH', 'ETIOPIA'),
  ('EG', 'EGY', 'EGYPT'),
  ('DJ', 'DJI', 'DJIBOUTI'),
  ('GA', 'GAB', 'GABON'),
  ('GM', 'GMB', 'GAMBIA'),
  ('GH', 'GHA', 'GHANA'),
  ('GN', 'GIN', 'GUINEA'),
  ('GW', 'GNB', 'GUINEA-BISSAU'),
  ('CM', 'CMR', 'KAMERUN'),
  ('CV', 'CPV', 'KAPP VERDE'),
  ('KE', 'KEN', 'KENYA'),
  ('CG', 'COG', 'KONGO, REPUBLIKKEN'),
  ('CD', 'COD', 'KONGO, DEN DEMOKR. REPUBL'),
  ('LS', 'LSO', 'LESOTHO'),
  ('LR', 'LBR', 'LIBERIA'),
  ('LY', 'LBY', 'LIBYA'),
  ('MG', 'MDG', 'MADAGASKAR'),
  ('MW', 'MWI', 'MALAWI'),
  ('ML', 'MLI', 'MALI'),
  ('MA', 'MAR', 'MAROKKO'),
  ('EH', 'ESH', 'VEST-SAHARA'),
  ('MR', 'MRT', 'MAURITANIA'),
  ('MU', 'MUS', 'MAURITIUS'),
  ('NA', 'NAM', 'NAMIBIA'),
  ('NE', 'NER', 'NIGER'),
  ('NG', 'NGA', 'NIGERIA'),
  ('MZ', 'MOZ', 'MOSAMBIK'),
  ('YT', 'MYT', 'MAYOTTE'),
  ('RE', 'REU', 'RéUNION'),
  ('ZW', 'ZWE', 'ZIMBABWE'),
  ('RW', 'RWA', 'RWANDA'),
  ('ST', 'STP', 'SAO TOME OG PRINCIPE'),
  ('SN', 'SEN', 'SENEGAL'),
  ('CF', 'CAF', 'SENTRALAFRIKANSKE REPUBL'),
  ('SC', 'SYC', 'SEYCHELLENE'),
  ('SL', 'SLE', 'SIERRA LEONE'),
  ('SO', 'SOM', 'SOMALIA'),
  ('SS', 'SSD', 'SØR-SUDAN'),
  ('SD', 'SDN', 'SUDAN'),
  ('SZ', 'SWZ', 'SWAZILAND'),
  ('ZA', 'ZAF', 'SØR-AFRIKA'),
  ('TZ', 'TZA', 'TANZANIA'),
  ('TD', 'TCD', 'TCHAD'),
  ('TG', 'TGO', 'TOGO'),
  ('TN', 'TUN', 'TUNISIA'),
  ('UG', 'UGA', 'UGANDA'),
  ('ZM', 'ZMB', 'ZAMBIA'),
  ('BF', 'BFA', 'BURKINA FASO'),
  ('AF', 'AFG', 'AFGHANISTAN'),
  ('AM', 'ARM', 'ARMENIA'),
  ('AZ', 'AZE', 'ASERBAJDSJAN'),
  ('BH', 'BHR', 'BAHRAIN'),
  ('BD', 'BGD', 'BANGLADESH'),
  ('BT', 'BTN', 'BHUTAN'),
  ('BN', 'BRN', 'BRUNEI'),
  ('MM', 'MMR', 'MYANMAR (BURMA)'),
  ('LK', 'LKA', 'SRI LANKA'),
  ('AE', 'ARE', 'DE ARABISKE EMIRATER'),
  ('PH', 'PHL', 'FILIPPINENE'),
  ('GE', 'GEO', 'GEORGIA'),
  ('TW', 'TWN', 'TAIWAN'),
  ('HK', 'HKG', 'HONGKONG'),
  ('IN', 'IND', 'INDIA'),
  ('ID', 'IDN', 'INDONESIA'),
  ('IQ', 'IRQ', 'IRAK'),
  ('IR', 'IRN', 'IRAN'),
  ('IL', 'ISR', 'ISRAEL'),
  ('JP', 'JPN', 'JAPAN'),
  ('JO', 'JOR', 'JORDAN'),
  ('KH', 'KHM', 'KAMBODSJA'),
  ('KZ', 'KAZ', 'KAZAKHSTAN'),
  ('CN', 'CHN', 'KINA'),
  ('KP', 'PRK', 'NORD-KOREA'),
  ('KR', 'KOR', 'SØR-KOREA'),
  ('KW', 'KWT', 'KUWAIT'),
  ('CY', 'CYP', 'KYPROS'),
  ('KG', 'KGZ', 'KIRGISISTAN'),
  ('LA', 'LAO', 'LAOS'),
  ('LB', 'LBN', 'LIBANON'),
  ('MO', 'MAC', 'MACAO'),
  ('MY', 'MYS', 'MALAYSIA'),
  ('MV', 'MDV', 'MALDIVENE'),
  ('MN', 'MNG', 'MONGOLIA'),
  ('OM', 'OMN', 'OMAN'),
  ('PS', 'PSE', 'PALESTINA'),
  ('NP', 'NPL', 'NEPAL'),
  ('PK', 'PAK', 'PAKISTAN'),
  ('TL', 'TLS', 'ØST-TIMOR'),
  ('QA', 'QAT', 'QATAR'),
  ('SA', 'SAU', 'SAUDI-ARABIA'),
  ('SG', 'SGP', 'SINGAPORE'),
  ('TJ', 'TJK', 'TADSJIKISTAN'),
  ('TM', 'TKM', 'TURKMENISTAN'),
  ('UZ', 'UZB', 'UZBEKISTAN'),
  ('SY', 'SYR', 'SYRIA'),
  ('TH', 'THA', 'THAILAND'),
  ('VN', 'VNM', 'VIETNAM'),
  ('YE', 'YEM', 'YEMEN'),
  ('VI', 'VIR', 'JOMFRUØYENE AM.'),
  ('BB', 'BRB', 'BARBADOS'),
  ('AG', 'ATG', 'ANTIGUA OG BARBUDA'),
  ('BZ', 'BLZ', 'BELIZE'),
  ('BS', 'BHS', 'BAHAMAS'),
  ('BM', 'BMU', 'BERMUDA'),
  ('VG', 'VGB', 'JOMFRUØYENE BRIT.'),
  ('CA', 'CAN', 'CANADA'),
  ('KY', 'CYM', 'CAYMANØYENE'),
  ('CR', 'CRI', 'COSTA RICA'),
  ('CU', 'CUB', 'CUBA'),
  ('DM', 'DMA', 'DOMINICA'),
  ('DO', 'DOM', 'DEN DOMINIKANSKE REP'),
  ('GD', 'GRD', 'GRENADA'),
  ('GP', 'GLP', 'GUADELOUPE'),
  ('GT', 'GTM', 'GUATEMALA'),
  ('HT', 'HTI', 'HAITI'),
  ('HN', 'HND', 'HONDURAS'),
  ('JM', 'JAM', 'JAMAICA'),
  ('MQ', 'MTQ', 'MARTINIQUE'),
  ('MX', 'MEX', 'MEXICO'),
  ('MS', 'MSR', 'MONTSERRAT'),
  ('AN', 'ANT', 'DE NEDERLANDSKE ANTILLENE'),
  ('AW', 'ABW', 'ARUBA'),
  ('SX', 'SXM', 'SINT MAARTEN'),
  ('BQ', 'BES', 'BONAIRE, ST EUSTATIUS OG SABA'),
  ('AI', 'AIA', 'ANGUILLA'),
  ('CW', 'CUW', 'CURACAO'),
  ('NI', 'NIC', 'NICARAGUA'),
  ('PA', 'PAN', 'PANAMA'),
  ('SV', 'SLV', 'EL SALVADOR'),
  ('PM', 'SPM', 'ST.PIERRE OG MIQUELON'),
  ('KN', 'KNA', 'ST.KITTS OG NEVIS'),
  ('LC', 'LCA', 'ST. LUCIA'),
  ('VC', 'VCT', 'ST.VINCENT OG GRENADINENE'),
  ('TT', 'TTO', 'TRINIDAD OG TOBAGO'),
  ('TC', 'TCA', 'TURKS/CAICOSØYENE'),
  ('US', 'USA', 'USA'),
  ('PR', 'PRI', 'PUERTO RICO'),
  ('MF', 'MAF', 'SAINT MARTIN'),
  ('BL', 'BLM', 'ST BARTHELEMY'),
  ('AR', 'ARG', 'ARGENTINA'),
  ('BO', 'BOL', 'BOLIVIA'),
  ('BR', 'BRA', 'BRASIL'),
  ('GY', 'GUY', 'GUYANA'),
  ('CL', 'CHL', 'CHILE'),
  ('CO', 'COL', 'COLOMBIA'),
  ('EC', 'ECU', 'ECUADOR'),
  ('FK', 'FLK', 'FALKLANDSØYENE'),
  ('GF', 'GUF', 'FRANSK GUYANA'),
  ('PY', 'PRY', 'PARAGUAY'),
  ('PE', 'PER', 'PERU'),
  ('SR', 'SUR', 'SURINAME'),
  ('UY', 'URY', 'URUGUAY'),
  ('VE', 'VEN', 'VENEZUELA'),
  ('AS', 'ASM', 'AM. SAMOA'),
  ('AU', 'AUS', 'AUSTRALIA'),
  ('SB', 'SLB', 'SALOMONØYENE'),
  ('CX', 'CXR', 'CHRISTMASØYA'),
  ('CC', 'CCK', 'KOKOSØYENE'),
  ('CK', 'COK', 'COOKØYENE'),
  ('FJ', 'FJI', 'FIJI'),
  ('VU', 'VUT', 'VANUATU'),
  ('TO', 'TON', 'TONGA'),
  ('PF', 'PYF', 'FRANSK POLYNESIA'),
  ('KI', 'KIR', 'KIRIBATI'),
  ('TV', 'TUV', 'TUVALU'),
  ('GU', 'GUM', 'GUAM'),
  ('NR', 'NRU', 'NAURU'),
  ('UM', 'UMI', 'MINDRE STILLEHAVSØYER'),
  ('NZ', 'NZL', 'NEW ZEALAND'),
  ('NU', 'NIU', 'NIUE'),
  ('NF', 'NFK', 'NORFOLKØYA'),
  ('FM', 'FSM', 'MIKRONESIAFØDERASJONEN'),
  ('PG', 'PNG', 'PAPUA NY-GUINEA'),
  ('PN', 'PCN', 'PITCAIRN'),
  ('TK', 'TKL', 'TOKELAU'),
  ('WS', 'WSM', 'VEST-SAMOA'),
  ('WF', 'WLF', 'WALLIS/FUTUNAØYENE'),
  ('NC', 'NCL', 'NY-KALEDONIA'),
  ('MH', 'MHL', 'MARSHALLØYENE'),
  ('PW', 'PLW', 'PALAU'),
  ('MP', 'MNP', 'NORD-MARIANENE'),
  ('AQ', 'ATA', 'ANTARKTIS'),
  ('AX', 'ALA', 'ÅLAND'),
  ('BV', 'BVT', 'BOUVETØYA'),
  ('GS', 'SGS', 'SØR-GEORGIA OG SANDWICHØYENE'),
  ('HM', 'HMD', 'HEARD- OG MCDONALDØYENE'),
  ('SJ', 'SJM', 'SVALBARD OG JAN MAYEN'),
  ('TF', 'ATF', 'DE FRANSKE TERRITORIENE I SØR'),
  ('DD', 'DDR', 'X-DDR'),
  ('YU', 'YUG', 'X-JUGOSLAVIA'),
  ('CS', 'CSK', 'X-TSJEKKOSLOVAKIA'),
  ('XA', 'XXA', 'X-XXA'),
  ('SU', 'SUN', 'X-SOVJETUNIONEN'),
  ('XX', 'XXX', 'STATSLØS'),
  ('YY', 'XUK', 'UKJENT'),
  ('ZZ', 'ZZZ', 'DIVERSE');
