-- create schema
CREATE SCHEMA IF NOT EXISTS "${SCHEMA}";

-- grant schema
GRANT USAGE ON SCHEMA "${SCHEMA}" TO "${APP-USER}";

-- grant on tables
ALTER DEFAULT PRIVILEGES FOR USER "${YUNIQL-USER}" IN SCHEMA "${SCHEMA}" GRANT
SELECT
, INSERT, UPDATE, REFERENCES, DELETE, TRUNCATE, TRIGGER ON TABLES TO "${APP-USER}";

-- grant on sequences
ALTER DEFAULT PRIVILEGES FOR USER "${YUNIQL-USER}" IN SCHEMA "${SCHEMA}" GRANT ALL ON SEQUENCES TO "${APP-USER}";
