name: Register Scan

on:
  schedule:
  - cron: '0 8 * * 1,4'
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'Dockerfile'
  pull_request:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'Dockerfile'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --tag altinn-register:${{github.sha}}

    - uses: Azure/container-scan@v0
      with:
        image-name: altinn-register:${{ github.sha }}
